#!/usr/bin/env python3
"""hall.sdf large hall world SDF model generator script.

    python3 generate_hall.py > hall.sdf
"""

import os
import sys

TEX = 'model://room_materials/materials/textures'

# Hall dimensions
X0, X1 = -12.0, 12.0
Y0, Y1 = -4.0, 14.0          # Y0 must match room.sdf (dock coordinates)
WALL_H = 2.2
WALL_T = 0.15
SEG = 3.0                    # Outer wall segment length

# Racks (2 blocks x 4 rows)
RACK_LEN = 8.0
RACK_DEPTH = 0.8
RACK_H = 1.8
RACK_YS = (1.8, 4.3, 6.8, 9.3)      # Rack center y -> aisle width 2.5-0.8 = 1.7 m
RACK_BLOCKS = ((-10.0, -2.0), (2.0, 10.0))   # (x_start, x_end)

# Office (North)
OFFICE_Y = 11.2              # Front wall y
OFFICE_D = 2.6               # Depth (front wall ~ north outer wall)
OFFICE_XS = ((-9.0, -5.0), (-3.0, 1.0), (3.0, 7.0))
DOOR_W = 0.9

PILLARS = ((-6.0, 0.6), (6.0, 0.6), (-6.0, 10.6), (6.0, 10.6))
PILLAR = 0.4

out = []
_tex = 0


def w(s=''):
    out.append(s)


def next_tex():
    global _tex
    t = _tex
    _tex += 1
    return '%s/hall_%03d.png' % (TEX, t)


def box_visual(name, pose, size, texture):
    w(f"""      <visual name="{name}">
        <pose>{pose}</pose>
        <geometry><box><size>{size}</size></box></geometry>
        <material>
          <ambient>1 1 1 1</ambient><diffuse>1 1 1 1</diffuse>
          <specular>0.05 0.05 0.05 1</specular>
          <pbr><metal><albedo_map>{texture}</albedo_map><roughness>0.9</roughness></metal></pbr>
        </material>
      </visual>""")


def box_collision(name, pose, size):
    w(f"""      <collision name="{name}">
        <pose>{pose}</pose>
        <geometry><box><size>{size}</size></box></geometry>
      </collision>""")


def colored_box(name, pose, size, rgb, collision=True):
    w(f"""      <visual name="{name}">
        <pose>{pose}</pose>
        <geometry><box><size>{size}</size></box></geometry>
        <material>
          <ambient>{rgb[0]} {rgb[1]} {rgb[2]} 1</ambient>
          <diffuse>{rgb[0]} {rgb[1]} {rgb[2]} 1</diffuse>
          <specular>0.1 0.1 0.1 1</specular>
        </material>
      </visual>""")
    if collision:
        box_collision(f'{name}_c', pose, size)


def slab(name, cx, cy, sx, sy, h, z=None):
    """Textured wall segment as independent model."""
    z = h / 2.0 if z is None else z
    w(f'    <model name="{name}">')
    w('      <static>true</static>')
    w(f'      <link name="link">')
    box_visual('v', f'{cx:.3f} {cy:.3f} {z:.3f} 0 0 0', f'{sx:.3f} {sy:.3f} {h:.3f}', next_tex())
    box_collision('c', f'{cx:.3f} {cy:.3f} {z:.3f} 0 0 0', f'{sx:.3f} {sy:.3f} {h:.3f}')
    w('      </link>')
    w('    </model>')


# ====================================================================
w('<?xml version="1.0" ?>')
w('<!-- Generated by generate_hall.py. Do not edit directly; modify generator. -->')
w('<sdf version="1.9">')
w('  <world name="hall">')
w("""
    <scene>
      <ambient>0.6 0.6 0.6 1.0</ambient>
      <background>0.8 0.85 0.9 1.0</background>
      <shadows>true</shadows>
      <grid>false</grid>
    </scene>

    <plugin filename="gz-sim-physics-system"
            name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system"
            name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system"
            name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system"
            name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>

    <include>
      <uri>model://ground_plane</uri>
    </include>

    <light type="directional" name="sun">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.6 0.6 0.6 1</diffuse><specular>0.1 0.1 0.1 1</specular>
      <direction>-0.5 0.2 -0.9</direction>
    </light>
    <light type="directional" name="sun2">
      <cast_shadows>false</cast_shadows>
      <pose>-8 5 8 0 0 0</pose>
      <diffuse>0.3 0.3 0.3 1</diffuse><specular>0.0 0.0 0.0 1</specular>
      <direction>0.4 -0.2 -0.8</direction>
    </light>
    <light type="directional" name="sun3">
      <cast_shadows>false</cast_shadows>
      <pose>8 5 8 0 0 0</pose>
      <diffuse>0.3 0.3 0.3 1</diffuse><specular>0.0 0.0 0.0 1</specular>
      <direction>-0.4 -0.2 -0.8</direction>
    </light>
""")

# Floor
w('    <model name="floor">')
w('      <static>true</static>')
w(f'      <pose>{(X0+X1)/2:.3f} {(Y0+Y1)/2:.3f} -0.005 0 0 0</pose>')
w('      <link name="link"><visual name="v">')
w(f'        <geometry><box><size>{X1-X0:.2f} {Y1-Y0:.2f} 0.01</size></box></geometry>')
w('        <material><diffuse>1 1 1 1</diffuse><pbr><metal>')
w(f'          <albedo_map>{TEX}/floor.png</albedo_map><roughness>0.95</roughness>')
w('        </metal></pbr></material>')
w('      </visual></link>')
w('    </model>')


def frange(a, b, step):
    v = a
    while v < b - 1e-6:
        yield v
        v += step


# Outer walls (unique texture per segment)
n_wall = 0
for x in frange(X0, X1, SEG):
    ln = min(SEG, X1 - x)
    slab(f'wall_s_{n_wall}', x + ln / 2, Y0 - WALL_T / 2, ln, WALL_T, WALL_H); n_wall += 1
    slab(f'wall_n_{n_wall}', x + ln / 2, Y1 + WALL_T / 2, ln, WALL_T, WALL_H); n_wall += 1
for y in frange(Y0, Y1, SEG):
    ln = min(SEG, Y1 - y)
    slab(f'wall_w_{n_wall}', X0 - WALL_T / 2, y + ln / 2, WALL_T, ln, WALL_H); n_wall += 1
    slab(f'wall_e_{n_wall}', X1 + WALL_T / 2, y + ln / 2, WALL_T, ln, WALL_H); n_wall += 1

# Racks
PANEL_T = 0.06
n_rack = 0
for bx0, bx1 in RACK_BLOCKS:
    length = min(RACK_LEN, bx1 - bx0)
    cx = (bx0 + bx1) / 2.0
    for ry in RACK_YS:
        # North/South long sides
        slab(f'rack_{n_rack}_s', cx, ry - RACK_DEPTH / 2, length, PANEL_T, RACK_H)
        slab(f'rack_{n_rack}_n', cx, ry + RACK_DEPTH / 2, length, PANEL_T, RACK_H)
        # West/East sides
        slab(f'rack_{n_rack}_w', cx - length / 2, ry, PANEL_T, RACK_DEPTH, RACK_H)
        slab(f'rack_{n_rack}_e', cx + length / 2, ry, PANEL_T, RACK_DEPTH, RACK_H)
        n_rack += 1

# Offices (one door per front wall)
n_off = 0
for ox0, ox1 in OFFICE_XS:
    door_c = (ox0 + ox1) / 2.0
    w_left = (door_c - DOOR_W / 2.0) - ox0
    w_right = ox1 - (door_c + DOOR_W / 2.0)
    slab(f'off_{n_off}_front_l', ox0 + w_left / 2.0, OFFICE_Y, w_left, WALL_T, WALL_H)
    slab(f'off_{n_off}_front_r', ox1 - w_right / 2.0, OFFICE_Y, w_right, WALL_T, WALL_H)
    slab(f'off_{n_off}_partition_w', ox0, OFFICE_Y + OFFICE_D / 2.0, WALL_T, OFFICE_D, WALL_H)
    slab(f'off_{n_off}_partition_e', ox1, OFFICE_Y + OFFICE_D / 2.0, WALL_T, OFFICE_D, WALL_H)
    n_off += 1

# Pillars
for i, (px, py) in enumerate(PILLARS):
    slab(f'pillar_{i}', px, py, PILLAR, PILLAR, WALL_H)

# Charging Dock Station
DOCK_X = 1.0
DOCK_WALL_Y = Y0 + WALL_T / 2.0
DOCK_PANEL_T = 0.05
DOCK_PANEL_W = 0.52
DOCK_PANEL_H = 0.45
DOCK_PLATE = 0.14
DOCK_MARKER_Z = 0.31
DOCK_MARKER_DX = (-0.16, 0.0, 0.16)
DOCK_MARKER_IDS = (1, 0, 2)
DOCK_PLATE_LAT = 0.055
DOCK_PLATE_W = 0.075
DOCK_PLATE_L = 0.10
DOCK_PLATE_Z = 0.04
DOCK_PLATE_BACK = 0.10
DOCK_COPPER = (0.72, 0.45, 0.20)
DOCK_ROBOT_Y = -3.60

_panel_front = DOCK_WALL_Y + DOCK_PANEL_T
_plate_t = 0.008
_plate_cy = _panel_front - 0.002 + _plate_t / 2.0

w('    <model name="dock_station">')
w('      <static>true</static>')
w('      <link name="link">')
box_visual('dock_panel',
           f'{DOCK_X} {DOCK_WALL_Y + DOCK_PANEL_T/2.0} {DOCK_PANEL_H/2.0} 0 0 0',
           f'{DOCK_PANEL_W} {DOCK_PANEL_T} {DOCK_PANEL_H}', f'{TEX}/dock_body.png')
box_collision('dock_panel_c',
              f'{DOCK_X} {DOCK_WALL_Y + DOCK_PANEL_T/2.0} {DOCK_PANEL_H/2.0} 0 0 0',
              f'{DOCK_PANEL_W} {DOCK_PANEL_T} {DOCK_PANEL_H}')
for _dx, _mid in zip(DOCK_MARKER_DX, DOCK_MARKER_IDS):
    box_visual(f'dock_marker_{_mid}',
               f'{DOCK_X + _dx} {_plate_cy} {DOCK_MARKER_Z} 0 0 0',
               f'{DOCK_PLATE} {_plate_t} {DOCK_PLATE}',
               f'{TEX}/dock_marker_{_mid}.png')
_plate_y = DOCK_ROBOT_Y + DOCK_PLATE_BACK
for _k, _s in enumerate((-1, 1)):
    colored_box(
        f'dock_copper_{_k}',
        f'{DOCK_X + _s * DOCK_PLATE_LAT} {_plate_y} {DOCK_PLATE_Z / 2.0} 0 0 0',
        f'{DOCK_PLATE_W} {DOCK_PLATE_L} {DOCK_PLATE_Z}',
        DOCK_COPPER)
w('      </link>')
w('    </model>')

w('  </world>')
w('</sdf>')

_yaml = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                     '..', '..', 'orinbot_navigation', 'config', 'docking.yaml')
_checked = 'Unchecked'
try:
    import re
    with open(_yaml) as f:
        m = re.search(r'home_dock:.*?pose:\s*\[\s*([\d.-]+)\s*,\s*([\d.-]+)', f.read(), re.S)
        if m:
            px, py = float(m.group(1)), float(m.group(2))
            if abs(px - DOCK_X) > 1e-3 or abs(py - DOCK_ROBOT_Y) > 1e-3:
                sys.stderr.write('ERROR: docking.yaml [%.3f, %.3f] != world [%.3f, %.3f]\n' % (px, py, DOCK_X, DOCK_ROBOT_Y))
                sys.exit(1)
        _checked = 'Matched [%.2f, %.2f]' % (px, py)
except OSError as e:                                        # noqa: BLE001
    _checked = 'Read failed (%s)' % e

sys.stdout.write('\n'.join(out) + '\n')

e = sys.stderr.write
e('Hall %.0f x %.0f m (%.0f m^2), wall height %.1f m\n'
  % (X1 - X0, Y1 - Y0, (X1 - X0) * (Y1 - Y0), WALL_H))
e('Outer walls %d / Racks %d / Office rooms %d / Pillars %d\n'
  % (n_wall, n_rack, n_off, len(PILLARS)))
e('Rack aisle width %.2f m, main corridor %.2f m, door width %.2f m\n'
  % (RACK_YS[1] - RACK_YS[0] - RACK_DEPTH,
     RACK_BLOCKS[1][0] - RACK_BLOCKS[0][1], DOOR_W))
e('Required textures: hall_000 ~ hall_%03d (%d images)\n' % (_tex - 1, _tex))
e('Dock: docking.yaml check: %s\n' % _checked)
