#!/usr/bin/env python3
"""maze.sdf maze world SDF model generator script.

    python3 generate_maze.py [width_m] > maze.sdf
"""

import sys

import numpy as np

TEX = 'model://room_materials/materials/textures'

SEED = 20260803
N = 7                  # Cell grid N x N
CORRIDOR = float(sys.argv[1]) if len(sys.argv) > 1 else 0.75
WALL_T = 0.10
WALL_H = 1.2
PITCH = CORRIDOR + WALL_T
BRAID = 0.30           # Ratio of dead ends to open for loops
NARROW = (0.55, 0.60, 0.70)   # Narrow entrance widths

rng = np.random.default_rng(SEED)
_tex = 0


def w(s=''):
    sys.stdout.write(s + '\n')


def next_tex():
    global _tex
    t = _tex
    _tex += 1
    return '%s/maze_%03d.png' % (TEX, t)


def cx(i):
    return (i - (N - 1) / 2.0) * PITCH


def slab(name, x, y, sx, sy, texture):
    """Wall segment model (visual + collision)."""
    w('    <model name="%s">' % name)
    w('      <static>true</static>')
    w('      <pose>%.4f %.4f %.4f 0 0 0</pose>' % (x, y, WALL_H / 2.0))
    w('      <link name="link">')
    w('        <visual name="v">')
    w('          <geometry><box><size>%.4f %.4f %.4f</size></box></geometry>' % (sx, sy, WALL_H))
    w('          <material><ambient>1 1 1 1</ambient><diffuse>1 1 1 1</diffuse>')
    w('            <specular>0.05 0.05 0.05 1</specular>')
    w('            <pbr><metal><albedo_map>%s</albedo_map><roughness>0.9</roughness></metal></pbr>' % texture)
    w('          </material>')
    w('        </visual>')
    w('        <collision name="c">')
    w('          <geometry><box><size>%.4f %.4f %.4f</size></box></geometry>' % (sx, sy, WALL_H))
    w('        </collision>')
    w('      </link>')
    w('    </model>')


# Maze generation
vw = [[True] * N for _ in range(N + 1)]
hw = [[True] * (N + 1) for _ in range(N)]

visited = [[False] * N for _ in range(N)]
stack = [(N // 2, N // 2)]
visited[N // 2][N // 2] = True
while stack:
    i, j = stack[-1]
    nbrs = []
    for di, dj, wtype, (wi, wj) in [(-1, 0, 'v', (i, j)), (1, 0, 'v', (i + 1, j)),
                                   (0, -1, 'h', (i, j)), (0, 1, 'h', (i, j + 1))]:
        ni, nj = i + di, j + dj
        if 0 <= ni < N and 0 <= nj < N and not visited[ni][nj]:
            nbrs.append((ni, nj, wtype, wi, wj))
    if not nbrs:
        stack.pop()
        continue
    ni, nj, wtype, wi, wj = nbrs[rng.integers(0, len(nbrs))]
    if wtype == 'v':
        vw[wi][wj] = False
    else:
        hw[wi][wj] = False
    visited[ni][nj] = True
    stack.append((ni, nj))


def openings(i, j):
    o = []
    if not vw[i][j]:
        o.append(('v', i, j))
    if not vw[i + 1][j]:
        o.append(('v', i + 1, j))
    if not hw[i][j]:
        o.append(('h', i, j))
    if not hw[i][j + 1]:
        o.append(('h', i, j + 1))
    return o


# Braiding -- open subset of dead ends to form loops
dead = [(i, j) for i in range(N) for j in range(N) if len(openings(i, j)) == 1]
for i, j in dead:
    if rng.random() > BRAID:
        continue
    candidates = []
    for di, dj, wtype, (wi, wj) in [(-1, 0, 'v', (i, j)), (1, 0, 'v', (i + 1, j)),
                                   (0, -1, 'h', (i, j)), (0, 1, 'h', (i, j + 1))]:
        ni, nj = i + di, j + dj
        if 0 <= ni < N and 0 <= nj < N:
            if (wtype == 'v' and vw[wi][wj]) or (wtype == 'h' and hw[wi][wj]):
                candidates.append((wtype, wi, wj))
    if not candidates:
        continue
    wtype, a, b = candidates[rng.integers(0, len(candidates))]
    if wtype == 'v':
        vw[a][b] = False
    else:
        hw[a][b] = False

# Narrow selected pocket entrances
dead = [(i, j) for i in range(N) for j in range(N) if len(openings(i, j)) == 1]
narrow = {}
for k, gap in enumerate(NARROW):
    if k >= len(dead):
        break
    i, j = dead[k]
    narrow[openings(i, j)[0]] = (gap, (i, j))

# SDF Output
w('<?xml version="1.0" ?>')
w('<!-- Generated by generate_maze.py. Modify generator script. -->')
w('<sdf version="1.9">')
w('  <world name="maze">')
w("""
    <scene>
      <ambient>0.6 0.6 0.6 1.0</ambient>
      <background>0.8 0.85 0.9 1.0</background>
      <shadows>true</shadows>
      <grid>false</grid>
    </scene>

    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>

    <include><uri>model://ground_plane</uri></include>

    <light type="directional" name="sun">
      <cast_shadows>true</cast_shadows><pose>0 0 8 0 0 0</pose>
      <diffuse>0.6 0.6 0.6 1</diffuse><specular>0.1 0.1 0.1 1</specular>
      <direction>-0.5 0.2 -0.9</direction>
    </light>
    <light type="directional" name="sun2">
      <cast_shadows>false</cast_shadows><pose>-4 3 6 0 0 0</pose>
      <diffuse>0.3 0.3 0.3 1</diffuse><specular>0.0 0.0 0.0 1</specular>
      <direction>0.5 -0.2 -0.8</direction>
    </light>
""")

span = N * PITCH / 2.0 + WALL_T
w('    <model name="floor">')
w('      <static>true</static>')
w('      <pose>0 0 -0.005 0 0 0</pose>')
w('      <link name="link"><visual name="v">')
w('        <geometry><box><size>%.3f %.3f 0.01</size></box></geometry>'
  % (2 * span, 2 * span))
w('        <material><diffuse>1 1 1 1</diffuse><pbr><metal>')
w('          <albedo_map>%s/floor.png</albedo_map><roughness>0.95</roughness>' % TEX)
w('        </metal></pbr></material>')
w('      </visual></link>')
w('    </model>')

n_full = n_narrow = 0

for i in range(N + 1):
    for j in range(N):
        x = cx(i) - PITCH / 2.0
        y = cx(j)
        if ('v', i, j) in narrow:
            gap, _ = narrow[('v', i, j)]
            stub = max(0.01, (PITCH - gap) / 2.0)
            slab(f'vw_{i}_{j}_a', x, y - (PITCH - stub) / 2.0, WALL_T, stub, next_tex())
            slab(f'vw_{i}_{j}_b', x, y + (PITCH - stub) / 2.0, WALL_T, stub, next_tex())
            n_narrow += 1
        elif vw[i][j]:
            slab(f'vw_{i}_{j}', x, y, WALL_T, PITCH, next_tex())
            n_full += 1

for i in range(N):
    for j in range(N + 1):
        x = cx(i)
        y = cx(j) - PITCH / 2.0
        if ('h', i, j) in narrow:
            gap, _ = narrow[('h', i, j)]
            stub = max(0.01, (PITCH - gap) / 2.0)
            slab(f'hw_{i}_{j}_a', x - (PITCH - stub) / 2.0, y, stub, WALL_T, next_tex())
            slab(f'hw_{i}_{j}_b', x + (PITCH - stub) / 2.0, y, stub, WALL_T, next_tex())
            n_narrow += 1
        elif hw[i][j]:
            slab(f'hw_{i}_{j}', x, y, PITCH, WALL_T, next_tex())
            n_full += 1

w('  </world>')
w('</sdf>')

e = sys.stderr.write
e('Maze %dx%d cells, corridor %.2f m, wall %.2f m -> overall %.2f x %.2f m\n'
  % (N, N, CORRIDOR, WALL_T, 2 * span, 2 * span))
e('Wall segments %d (full %d + narrow stubs %d)\n'
  % (_tex, n_full, n_narrow))
e('Required textures: maze_000.png ~ maze_%03d.png (%d images)\n' % (_tex - 1, _tex))
