#!/usr/bin/env python3
"""office.sdf office world SDF model generator script.

    python3 generate_office.py > office.sdf
"""

import math
import os
import re
import sys

TEX = 'model://room_materials/materials/textures'

X0, X1 = -10.0, 10.0
Y0, Y1 = -4.0, 10.0              # Y0 fixed for dock coordinates
WALL_H = 2.4
WALL_T = 0.12
SEG = 2.5

COR_A = (-0.9, 0.9)              # South corridor (E-W)
COR_B = (5.1, 6.9)               # North corridor (E-W)
PART_X = (-6.0, -2.0, 2.0, 6.0)  # Room partition x coordinates
DOOR = 0.9

out = []
_tex = 0


def w(s=''):
    out.append(s)


def tex():
    global _tex
    t = _tex
    _tex += 1
    return '%s/office_%03d.png' % (TEX, t)


def vis(name, pose, size, texture):
    w(f"""      <visual name="{name}">
        <pose>{pose}</pose>
        <geometry><box><size>{size}</size></box></geometry>
        <material>
          <ambient>1 1 1 1</ambient><diffuse>1 1 1 1</diffuse>
          <specular>0.05 0.05 0.05 1</specular>
          <pbr><metal><albedo_map>{texture}</albedo_map><roughness>0.9</roughness></metal></pbr>
        </material>
      </visual>""")


def col(name, pose, size):
    w(f"""      <collision name="{name}">
        <pose>{pose}</pose>
        <geometry><box><size>{size}</size></box></geometry>
      </collision>""")


def slab(name, cx, cy, sx, sy, h=WALL_H):
    w(f'    <model name="{name}">')
    w('      <static>true</static>')
    w('      <link name="link">')
    vis('v', f'{cx:.3f} {cy:.3f} {h/2:.3f} 0 0 0', f'{sx:.3f} {sy:.3f} {h:.3f}', tex())
    col('c', f'{cx:.3f} {cy:.3f} {h/2:.3f} 0 0 0', f'{sx:.3f} {sy:.3f} {h:.3f}')
    w('      </link>')
    w('    </model>')


def furniture(name, cx, cy, sx, sy, sz, z0, texture):
    """Furniture item for visual feature extraction."""
    w(f'    <model name="{name}">')
    w('      <static>true</static>')
    w(f'      <pose>{cx:.3f} {cy:.3f} {z0 + sz/2:.3f} 0 0 0</pose>')
    w('      <link name="link">')
    vis('v', '0 0 0 0 0 0', f'{sx} {sy} {sz}', f'{TEX}/{texture}')
    col('c', '0 0 0 0 0 0', f'{sx} {sy} {sz}')
    w('      </link>')
    w('    </model>')


def person(name, cx, cy, rgb):
    """Pedestrian model (controlled via velocity by people_sim.py)."""
    w(f'    <model name="{name}">')
    w(f'      <pose>{cx:.2f} {cy:.2f} 0.85 0 0 0</pose>')
    w('      <link name="link">')
    w('        <gravity>false</gravity>')
    w('        <inertial><mass>70.0</mass><inertia><ixx>17.0</ixx><iyy>17.0</iyy><izz>1.7</izz></inertia></inertial>')
    w('        <visual name="v">')
    w('          <geometry><cylinder><radius>0.22</radius><length>1.70</length></cylinder></geometry>')
    w(f'          <material><ambient>{rgb}</ambient><diffuse>{rgb}</diffuse></material>')
    w('        </visual>')
    w('        <collision name="c">')
    w('          <geometry><cylinder><radius>0.22</radius><length>1.70</length></cylinder></geometry>')
    w('        </collision>')
    w('      </link>')
    w('      <plugin filename="gz-sim-velocity-control-system" name="gz::sim::systems::VelocityControl">')
    w(f'        <topic>/model/{name}/cmd_vel</topic>')
    w('      </plugin>')
    w('    </model>')


def frange(a, b, s):
    v = a
    while v < b - 1e-6:
        yield v
        v += s


w('<?xml version="1.0" ?>')
w('<!-- Generated by generate_office.py. Modify generator script. -->')
w('<sdf version="1.9">')
w('  <world name="office">')
w("""
    <scene>
      <ambient>0.65 0.65 0.65 1.0</ambient>
      <background>0.85 0.88 0.92 1.0</background>
      <shadows>true</shadows>
      <grid>false</grid>
    </scene>

    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>

    <include><uri>model://ground_plane</uri></include>

    <light type="directional" name="ceil1">
      <cast_shadows>true</cast_shadows><pose>0 0 6 0 0 0</pose>
      <diffuse>0.55 0.55 0.55 1</diffuse><specular>0.05 0.05 0.05 1</specular>
      <direction>-0.3 0.2 -0.9</direction>
    </light>
    <light type="directional" name="ceil2">
      <cast_shadows>false</cast_shadows><pose>-5 3 6 0 0 0</pose>
      <diffuse>0.35 0.35 0.35 1</diffuse><specular>0.0 0.0 0.0 1</specular>
      <direction>0.3 -0.1 -0.9</direction>
    </light>
    <light type="directional" name="ceil3">
      <cast_shadows>false</cast_shadows><pose>5 3 6 0 0 0</pose>
      <diffuse>0.35 0.35 0.35 1</diffuse><specular>0.0 0.0 0.0 1</specular>
      <direction>-0.3 -0.1 -0.9</direction>
    </light>
""")

w('    <model name="floor">')
w('      <static>true</static>')
w(f'      <pose>{(X0+X1)/2:.2f} {(Y0+Y1)/2:.2f} -0.005 0 0 0</pose>')
w('      <link name="link"><visual name="v">')
w(f'        <geometry><box><size>{X1-X0} {Y1-Y0} 0.01</size></box></geometry>')
w('        <material><diffuse>1 1 1 1</diffuse><pbr><metal>')
w(f'          <albedo_map>{TEX}/floor.png</albedo_map><roughness>0.95</roughness>')
w('        </metal></pbr></material>')
w('      </visual></link>')
w('    </model>')

# Outer walls
n = 0
for x in frange(X0, X1, SEG):
    ln = min(SEG, X1 - x)
    slab(f'w_s{n}', x + ln / 2, Y0 - WALL_T / 2, ln, WALL_T); n += 1
    slab(f'w_n{n}', x + ln / 2, Y1 + WALL_T / 2, ln, WALL_T); n += 1
for y in frange(Y0, Y1, SEG):
    ln = min(SEG, Y1 - y)
    slab(f'w_w{n}', X0 - WALL_T / 2, y + ln / 2, WALL_T, ln); n += 1
    slab(f'w_e{n}', X1 + WALL_T / 2, y + ln / 2, WALL_T, ln); n += 1
n_wall = n


def corridor_wall(tag, y, xs):
    edges = [X0] + list(xs) + [X1]
    k = 0
    for a, b in zip(edges[:-1], edges[1:]):
        dc = (a + b) / 2.0
        w1 = (dc - DOOR / 2.0) - a
        w2 = b - (dc + DOOR / 2.0)
        slab(f'{tag}_l{k}', a + w1 / 2.0, y, w1, WALL_T)
        slab(f'{tag}_r{k}', b - w2 / 2.0, y, w2, WALL_T)
        k += 1


corridor_wall('cA_n', COR_A[1], PART_X)
corridor_wall('cB_s', COR_B[0], PART_X)
corridor_wall('cB_n', COR_B[1], PART_X)

for i, px in enumerate(PART_X):
    slab(f'p1_{i}', px, (COR_A[1] + COR_B[0]) / 2, WALL_T, COR_B[0] - COR_A[1])
    slab(f'p2_{i}', px, (COR_B[1] + Y1) / 2, WALL_T, Y1 - COR_B[1])

# Furniture
POSTERS = ['poster%d.png' % i for i in range(1, 9)]
nf = 0
room_bands = [(COR_A[1], COR_B[0]), (COR_B[1], Y1)]
edges = [X0] + list(PART_X) + [X1]
for band_i, (by0, by1) in enumerate(room_bands):
    for r, (a, b) in enumerate(zip(edges[:-1], edges[1:])):
        rx = (a + b) / 2.0
        ry = (by0 + by1) / 2.0
        rw = b - a - 0.4
        rh = by1 - by0 - 0.4

        furniture(f'desk_{nf}', rx - 0.3, ry + 0.3, 1.2, 0.7, 0.75, 0.0, 'crate.png')
        furniture(f'chair_{nf}', rx - 0.3, ry - 0.3, 0.5, 0.5, 0.45, 0.0, 'crate.png')
        furniture(f'shelf_{nf}', rx + rw / 2.0 - 0.4, ry, 0.4, 1.0, 1.6, 0.0, POSTERS[nf % len(POSTERS)])
        nf += 1

# Pedestrians
ROBOT_SPAWN = (0.0, -2.0)
_people = [
    ('person_0', -8.0, 0.0, '0.85 0.30 0.25 1'),
    ('person_1', 8.0, 6.0, '0.25 0.45 0.85 1'),
    ('person_2', -8.0, -1.6, '0.25 0.70 0.35 1'),
]
for _p in _people:
    d0 = math.dist((_p[1], _p[2]), ROBOT_SPAWN)
    if d0 < 1.5:
        sys.stderr.write('ERROR: %s is only %.2f m from robot spawn (requires >=1.5)\n' % (_p[0], d0))
        sys.exit(1)
    person(*_p)

# Charging Dock Station
DOCK_X, DOCK_ROBOT_Y = 1.0, -3.60
DOCK_WALL_Y = Y0 + WALL_T / 2
DOCK_PANEL_T, DOCK_PANEL_W, DOCK_PANEL_H = 0.05, 0.52, 0.45
DOCK_PLATE, DOCK_MARKER_Z = 0.14, 0.31
DOCK_MARKER_DX, DOCK_MARKER_IDS = (-0.16, 0.0, 0.16), (1, 0, 2)
DOCK_PLATE_LAT, DOCK_PLATE_W, DOCK_PLATE_L = 0.055, 0.075, 0.10
DOCK_PLATE_Z, DOCK_PLATE_BACK = 0.04, 0.10
_pf = DOCK_WALL_Y + DOCK_PANEL_T
_pt = 0.008
_pcy = _pf - 0.002 + _pt / 2.0

w('    <model name="dock_station">')
w('      <static>true</static>')
w('      <link name="link">')
vis('dock_panel', f'{DOCK_X} {DOCK_WALL_Y + DOCK_PANEL_T/2} {DOCK_PANEL_H/2} 0 0 0',
    f'{DOCK_PANEL_W} {DOCK_PANEL_T} {DOCK_PANEL_H}', f'{TEX}/dock_body.png')
col('dock_panel_c', f'{DOCK_X} {DOCK_WALL_Y + DOCK_PANEL_T/2} {DOCK_PANEL_H/2} 0 0 0',
    f'{DOCK_PANEL_W} {DOCK_PANEL_T} {DOCK_PANEL_H}')
for _dx, _mid in zip(DOCK_MARKER_DX, DOCK_MARKER_IDS):
    vis(f'dock_marker_{_mid}', f'{DOCK_X + _dx} {_pcy} {DOCK_MARKER_Z} 0 0 0',
        f'{DOCK_PLATE} {_pt} {DOCK_PLATE}', f'{TEX}/dock_marker_{_mid}.png')
_py = DOCK_ROBOT_Y + DOCK_PLATE_BACK
for _k, _s in enumerate((-1, 1)):
    p = f'{DOCK_X + _s*DOCK_PLATE_LAT} {_py} {DOCK_PLATE_Z/2} 0 0 0'
    s = f'{DOCK_PLATE_W} {DOCK_PLATE_L} {DOCK_PLATE_Z}'
    vis(f'dock_plate_{_k}', p, s, f'{TEX}/crate.png')
    col(f'dock_plate_{_k}_c', p, s)
w('      </link>')
w('    </model>')

w('  </world>')
w('</sdf>')

_y = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                      '..', '..', 'orinbot_navigation', 'config', 'docking.yaml'))
_chk = 'Unchecked'
try:
    m = re.search(r'home_dock:.*?pose:\s*\[([-0-9.]+),\s*([-0-9.]+)', open(_y).read(), re.S)
    if m:
        px, py = float(m.group(1)), float(m.group(2))
        if abs(px - DOCK_X) > 1e-3 or abs(py - DOCK_ROBOT_Y) > 1e-3:
            sys.stderr.write('ERROR: docking.yaml [%.3f, %.3f] != world [%.3f, %.3f]\n' % (px, py, DOCK_X, DOCK_ROBOT_Y))
            sys.exit(1)
        _chk = 'Matched [%.2f, %.2f]' % (px, py)
except OSError as exc:                                    # noqa: BLE001
    _chk = 'Read failed (%s)' % exc

sys.stdout.write('\n'.join(out) + '\n')
e = sys.stderr.write
e('Office %.0f x %.0f m, wall height %.1f m\n'
  % (X1 - X0, Y1 - Y0, WALL_H))
e('Corridor A y %.1f~%.1f (%.1f m), Corridor B y %.1f~%.1f (%.1f m), Door %.2f m\n'
  % (COR_A[0], COR_A[1], COR_A[1] - COR_A[0],
     COR_B[0], COR_B[1], COR_B[1] - COR_B[0], DOOR))
e('Rooms %d, Furniture %d sets, Pedestrians 3\n'
  % ((len(edges) - 1) * len(room_bands), nf))
e('Docking check: %s\n' % _chk)
