#!/usr/bin/env python3
"""Large indoor warehouse world for final integration testing.

    python3 generate_hall.py > hall.sdf        (summary goes to stderr)

room.sdf (10x8 m) and maze.sdf (6x6 m) are not deployment scale. This world
tests exploration convergence in open space, SLAM drift and loop closure over
long runs, RTAB-Map node growth, and a mix of corridors and open floor.

24 x 18 m (x -12..12, y -4..14). The south wall sits at y = -4.0, the same as
room.sdf, so docking.yaml's dock pose carries over; the generator reads that
file and aborts on a mismatch.

Layout: loading bay (y -4..1, dock on the south wall), two rack blocks of
four rows with 1.7 m aisles, a 3 m central corridor, three offices with 0.9 m
doors, and four structural pillars.

Unique texture per wall face (generate_textures.py hall); reuse breaks loop
closure. Rack faces differ on all four sides because the two long faces of
one rack are seen from different aisles.
"""

import os
import sys

TEX = 'model://room_materials/materials/textures'

# ---- Hall dimensions ----
X0, X1 = -12.0, 12.0
Y0, Y1 = -4.0, 14.0          # Y0 must match room.sdf (dock pose)
WALL_H = 2.2
WALL_T = 0.15
SEG = 3.0                    # outer wall segment length

# ---- Racks (2 blocks x 4 rows) ----
RACK_LEN = 8.0
RACK_DEPTH = 0.8
RACK_H = 1.8
RACK_YS = (1.8, 4.3, 6.8, 9.3)      # rack centres -> 1.7 m aisles
RACK_BLOCKS = ((-10.0, -2.0), (2.0, 10.0))   # (x start, x end)

# ---- Offices (north) ----
OFFICE_Y = 11.2              # front wall y
OFFICE_D = 2.6               # depth, front wall to north wall
OFFICE_XS = ((-9.0, -5.0), (-3.0, 1.0), (3.0, 7.0))
DOOR_W = 0.9

PILLARS = ((-6.0, 0.6), (6.0, 0.6), (-6.0, 10.6), (6.0, 10.6))
PILLAR = 0.4

out = []
_tex = 0


def w(s=''):
    out.append(s)


def next_tex():
    global _tex
    t = _tex
    _tex += 1
    return '%s/hall_%03d.png' % (TEX, t)


def box_visual(name, pose, size, texture):
    w(f"""      <visual name="{name}">
        <pose>{pose}</pose>
        <geometry><box><size>{size}</size></box></geometry>
        <material>
          <diffuse>1 1 1 1</diffuse>
          <pbr><metal>
            <albedo_map>{texture}</albedo_map>
            <roughness>0.9</roughness>
          </metal></pbr>
        </material>
      </visual>""")


def box_collision(name, pose, size):
    w(f"""      <collision name="{name}">
        <pose>{pose}</pose>
        <geometry><box><size>{size}</size></box></geometry>
      </collision>""")


def colored_box(name, pose, size, rgb, collision=True):
    w(f"""      <visual name="{name}">
        <pose>{pose}</pose>
        <geometry><box><size>{size}</size></box></geometry>
        <material>
          <ambient>{rgb[0]} {rgb[1]} {rgb[2]} 1</ambient>
          <diffuse>{rgb[0]} {rgb[1]} {rgb[2]} 1</diffuse>
          <specular>0.3 0.3 0.3 1</specular>
        </material>
      </visual>""")
    if collision:
        box_collision(f'{name}_c', pose, size)


def slab(name, cx, cy, sx, sy, h, z=None):
    """One textured wall piece as its own model."""
    z = h / 2.0 if z is None else z
    w(f'    <model name="{name}">')
    w('      <static>true</static>')
    w(f'      <pose>{cx:.4f} {cy:.4f} {z:.4f} 0 0 0</pose>')
    w('      <link name="link">')
    box_collision('c', '0 0 0 0 0 0', f'{sx:.4f} {sy:.4f} {h:.4f}')
    box_visual('v', '0 0 0 0 0 0', f'{sx:.4f} {sy:.4f} {h:.4f}', next_tex())
    w('      </link>')
    w('    </model>')


# ====================================================================
w('<?xml version="1.0" ?>')
w('<!-- Generated by generate_hall.py. Edit the generator, not this file. -->')
w('<sdf version="1.9">')
w('  <world name="hall">')
w("""
    <physics name="1ms" type="ignored">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>

    <plugin filename="gz-sim-physics-system"
            name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system"
            name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system"
            name="gz::sim::systems::SceneBroadcaster"/>
    <!-- Required for camera/depth rendering -->
    <plugin filename="gz-sim-sensors-system"
            name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-imu-system"
            name="gz::sim::systems::Imu"/>
    <plugin filename="gz-sim-contact-system"
            name="gz::sim::systems::Contact"/>

    <gravity>0 0 -9.8</gravity>

    <scene>
      <ambient>0.65 0.65 0.65 1</ambient>
      <background>0.75 0.82 0.9 1</background>
      <shadows>true</shadows>
    </scene>

    <!-- Three lights: a shadowed area with no features stalls VSLAM. -->
    <light type="directional" name="sun">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.6 0.6 0.6 1</diffuse>
      <specular>0.1 0.1 0.1 1</specular>
      <direction>-0.4 0.3 -0.9</direction>
    </light>
    <light type="directional" name="fill1">
      <cast_shadows>false</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.3 0.3 0.34 1</diffuse>
      <specular>0 0 0 1</specular>
      <direction>0.5 -0.4 -0.8</direction>
    </light>
    <light type="directional" name="fill2">
      <cast_shadows>false</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.25 0.25 0.28 1</diffuse>
      <specular>0 0 0 1</specular>
      <direction>0.1 0.9 -0.6</direction>
    </light>

    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>200 200</size></plane></geometry>
          <surface><friction><ode><mu>1.0</mu><mu2>1.0</mu2></ode></friction></surface>
        </collision>
      </link>
    </model>
""")

# ---- Floor (top exactly at z=0 to avoid z-fighting with ground_plane) ----
w('    <model name="floor">')
w('      <static>true</static>')
w(f'      <pose>{(X0+X1)/2:.3f} {(Y0+Y1)/2:.3f} -0.005 0 0 0</pose>')
w('      <link name="link"><visual name="v">')
w(f'        <geometry><box><size>{X1-X0:.2f} {Y1-Y0:.2f} 0.01</size></box></geometry>')
w('        <material><diffuse>1 1 1 1</diffuse><pbr><metal>')
w(f'          <albedo_map>{TEX}/floor.png</albedo_map><roughness>0.95</roughness>')
w('        </metal></pbr></material>')
w('      </visual></link>')
w('    </model>')


def frange(a, b, step):
    v = a
    while v < b - 1e-6:
        yield v
        v += step


# ---- Outer walls, unique texture per segment ----
n_wall = 0
for x in frange(X0, X1, SEG):
    ln = min(SEG, X1 - x)
    slab(f'wall_s_{n_wall}', x + ln / 2, Y0 - WALL_T / 2, ln, WALL_T, WALL_H); n_wall += 1
    slab(f'wall_n_{n_wall}', x + ln / 2, Y1 + WALL_T / 2, ln, WALL_T, WALL_H); n_wall += 1
for y in frange(Y0, Y1, SEG):
    ln = min(SEG, Y1 - y)
    slab(f'wall_w_{n_wall}', X0 - WALL_T / 2, y + ln / 2, WALL_T, ln, WALL_H); n_wall += 1
    slab(f'wall_e_{n_wall}', X1 + WALL_T / 2, y + ln / 2, WALL_T, ln, WALL_H); n_wall += 1

# ---- Racks: each face its own panel, seen from different aisles ----
PANEL_T = 0.06
n_rack = 0
for bx0, bx1 in RACK_BLOCKS:
    length = min(RACK_LEN, bx1 - bx0)
    cx = (bx0 + bx1) / 2.0
    for ry in RACK_YS:
        # Long faces, south/north
        slab(f'rack_{n_rack}_s', cx, ry - RACK_DEPTH / 2, length, PANEL_T, RACK_H)
        slab(f'rack_{n_rack}_n', cx, ry + RACK_DEPTH / 2, length, PANEL_T, RACK_H)
        # End faces, west/east
        slab(f'rack_{n_rack}_w', cx - length / 2, ry, PANEL_T, RACK_DEPTH, RACK_H)
        slab(f'rack_{n_rack}_e', cx + length / 2, ry, PANEL_T, RACK_DEPTH, RACK_H)
        n_rack += 1

# ---- Offices, one door each ----
n_off = 0
for ox0, ox1 in OFFICE_XS:
    # Front wall split either side of the door
    door_c = (ox0 + ox1) / 2.0
    left = door_c - DOOR_W / 2 - ox0
    right = ox1 - (door_c + DOOR_W / 2)
    if left > 0.05:
        slab(f'off_{n_off}_fl', ox0 + left / 2, OFFICE_Y, left, WALL_T, WALL_H)
    if right > 0.05:
        slab(f'off_{n_off}_fr', ox1 - right / 2, OFFICE_Y, right, WALL_T, WALL_H)
    # Side partitions up to the north wall
    depth = Y1 - OFFICE_Y
    slab(f'off_{n_off}_l', ox0, OFFICE_Y + depth / 2, WALL_T, depth, WALL_H)
    slab(f'off_{n_off}_r', ox1, OFFICE_Y + depth / 2, WALL_T, depth, WALL_H)
    n_off += 1

# ---- Pillars ----
for i, (px, py) in enumerate(PILLARS):
    slab(f'pillar_{i}', px, py, PILLAR, PILLAR, WALL_H)

# ====================================================================
# Charging dock
#
# These constants must match generate_room.py, docking.yaml and
# orinbot.urdf.xacro. A mismatch means visible markers that never make
# contact, so docking.yaml is read below and a mismatch aborts.
DOCK_X = 1.0
DOCK_WALL_Y = Y0 + WALL_T / 2.0
DOCK_PANEL_T = 0.05
DOCK_PANEL_W = 0.52
DOCK_PANEL_H = 0.45
DOCK_PLATE = 0.14
DOCK_MARKER_Z = 0.31
DOCK_MARKER_DX = (-0.16, 0.0, 0.16)
DOCK_MARKER_IDS = (1, 0, 2)
DOCK_PLATE_LAT = 0.055
DOCK_PLATE_W = 0.075
DOCK_PLATE_L = 0.10
DOCK_PLATE_Z = 0.04
DOCK_PLATE_BACK = 0.10
DOCK_COPPER = (0.72, 0.45, 0.20)
# Must match docking.yaml's reverse_dock: the plate position flips with it.
# Geometry rationale is in generate_room.py.
REVERSE_DOCK = True
DOCK_ROBOT_Y = -3.67 if REVERSE_DOCK else -3.60

_panel_front = DOCK_WALL_Y + DOCK_PANEL_T
_plate_t = 0.008
_plate_cy = _panel_front - 0.002 + _plate_t / 2.0

w('    <model name="dock_station">')
w('      <static>true</static>')
w('      <link name="link">')
box_visual('dock_panel',
           f'{DOCK_X} {DOCK_WALL_Y + DOCK_PANEL_T/2.0} {DOCK_PANEL_H/2.0} 0 0 0',
           f'{DOCK_PANEL_W} {DOCK_PANEL_T} {DOCK_PANEL_H}', f'{TEX}/dock_body.png')
box_collision('dock_panel_c',
              f'{DOCK_X} {DOCK_WALL_Y + DOCK_PANEL_T/2.0} {DOCK_PANEL_H/2.0} 0 0 0',
              f'{DOCK_PANEL_W} {DOCK_PANEL_T} {DOCK_PANEL_H}')
for _dx, _mid in zip(DOCK_MARKER_DX, DOCK_MARKER_IDS):
    box_visual(f'dock_marker_{_mid}',
               f'{DOCK_X + _dx} {_plate_cy} {DOCK_MARKER_Z} 0 0 0',
               f'{DOCK_PLATE} {_plate_t} {DOCK_PLATE}',
               f'{TEX}/dock_marker_{_mid}.png')
# The pogo pins sit behind the robot, so reverse docking puts the plates
# toward the wall.
_plate_y = DOCK_ROBOT_Y + (-DOCK_PLATE_BACK if REVERSE_DOCK else DOCK_PLATE_BACK)
for _k, _s in enumerate((-1, 1)):
    colored_box(
        f'dock_plate_{_k}',
        f'{DOCK_X + _s * DOCK_PLATE_LAT} {_plate_y} {DOCK_PLATE_Z/2.0} 0 0 0',
        f'{DOCK_PLATE_W} {DOCK_PLATE_L} {DOCK_PLATE_Z}',
        DOCK_COPPER)
w('      </link>')
w('    </model>')

w('  </world>')
w('</sdf>')

# ---- Cross-check against docking.yaml ----
_yaml = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                     '..', '..', 'orinbot_navigation', 'config', 'docking.yaml')
_checked = 'not checked'
try:
    import re
    with open(os.path.normpath(_yaml)) as f:
        m = re.search(r'home_dock:.*?pose:\s*\[([-0-9.]+),\s*([-0-9.]+)', f.read(), re.S)
    if m:
        px, py = float(m.group(1)), float(m.group(2))
        if abs(px - DOCK_X) > 1e-6 or abs(py - DOCK_ROBOT_Y) > 1e-6:
            sys.stderr.write(
                'ERROR: docking.yaml home_dock.pose [%.3f, %.3f] does not '
                'match this world dock [%.3f, %.3f]\n' % (px, py, DOCK_X, DOCK_ROBOT_Y))
            sys.exit(1)
        _checked = 'match [%.2f, %.2f]' % (px, py)
except OSError as e:                                        # noqa: BLE001
    _checked = 'read failed (%s)' % e

sys.stdout.write('\n'.join(out) + '\n')

e = sys.stderr.write
e('hall %.0f x %.0f m (%.0f m^2), wall height %.1f m\n'
  % (X1 - X0, Y1 - Y0, (X1 - X0) * (Y1 - Y0), WALL_H))
e('%d wall pieces / %d racks (%d faces) / %d offices / %d pillars\n'
  % (n_wall, n_rack, n_rack * 4, n_off, len(PILLARS)))
e('aisle %.2f m, central corridor %.2f m, office door %.2f m\n'
  % (RACK_YS[1] - RACK_YS[0] - RACK_DEPTH,
     RACK_BLOCKS[1][0] - RACK_BLOCKS[0][1], DOOR_W))
e('textures needed: hall_000 ~ hall_%03d  (%d)\n' % (_tex - 1, _tex))
e('  -> set N_HALL_SEGMENTS >= %d in generate_textures.py\n' % _tex)
e('     python3 generate_textures.py hall\n')
e('dock: docking.yaml cross-check %s\n' % _checked)
e('suggested spawn: (0, 0), open loading bay, %.1f m from the dock\n'
  % ((0 - DOCK_ROBOT_Y) ** 2) ** 0.5)
