#!/usr/bin/env python3
"""room.sdf generator.

Walls and floor are split into 2 m segments so textures stay sharp enough
for feature extraction (256 px/m instead of 64 px/m across a whole wall).
That is ~60 segments, which is why this is generated.

    python3 generate_room.py > room.sdf

Edit the constants here and re-export to change the layout. room.sdf is
committed, so this normally does not need to run.
"""

import math
import sys

TEX = 'model://room_materials/materials/textures'

ROOM_X = 5.0          # wall centre distance, x
ROOM_Y = 4.0          # wall centre distance, y
WALL_H = 1.2
WALL_T = 0.1
SEG = 2.0             # segment length

out = []


def w(s=''):
    out.append(s)


def pbr(texture, roughness=0.9):
    return f"""        <material>
          <ambient>1 1 1 1</ambient>
          <diffuse>1 1 1 1</diffuse>
          <specular>0.05 0.05 0.05 1</specular>
          <pbr>
            <metal>
              <albedo_map>{TEX}/{texture}</albedo_map>
              <metalness>0.0</metalness>
              <roughness>{roughness}</roughness>
            </metal>
          </pbr>
        </material>"""


def box_visual(name, pose, size, texture):
    w(f"""      <visual name="{name}">
        <pose>{pose}</pose>
        <geometry><box><size>{size}</size></box></geometry>
{pbr(texture)}
      </visual>""")


def box_collision(name, pose, size):
    w(f"""      <collision name="{name}">
        <pose>{pose}</pose>
        <geometry><box><size>{size}</size></box></geometry>
      </collision>""")


def frange(a, b, step):
    v = a
    while v < b - 1e-9:
        yield v
        v += step


# ----------------------------------------------------------------------
w('<?xml version="1.0" ?>')
w('<!-- Generated by generate_room.py. Edit the generator, not this file. -->')
w('<sdf version="1.9">')
w('  <world name="room">')
w("""
    <physics name="1ms" type="ignored">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>

    <plugin filename="gz-sim-physics-system"
            name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system"
            name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system"
            name="gz::sim::systems::SceneBroadcaster"/>
    <!-- Required for camera/depth rendering -->
    <plugin filename="gz-sim-sensors-system"
            name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-imu-system"
            name="gz::sim::systems::Imu"/>
    <plugin filename="gz-sim-contact-system"
            name="gz::sim::systems::Contact"/>

    <gravity>0 0 -9.8</gravity>

    <scene>
      <ambient>0.6 0.6 0.6 1</ambient>
      <background>0.75 0.82 0.9 1</background>
      <shadows>true</shadows>
    </scene>

    <!-- Two lights so shadows do not wipe out feature points -->
    <light type="directional" name="sun">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 8 0 0 0</pose>
      <diffuse>0.7 0.7 0.7 1</diffuse>
      <specular>0.1 0.1 0.1 1</specular>
      <direction>-0.4 0.3 -0.9</direction>
    </light>
    <light type="directional" name="fill">
      <cast_shadows>false</cast_shadows>
      <pose>0 0 8 0 0 0</pose>
      <diffuse>0.35 0.35 0.4 1</diffuse>
      <specular>0 0 0 1</specular>
      <direction>0.5 -0.4 -0.8</direction>
    </light>

    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>100 100</size></plane></geometry>
          <surface><friction><ode><mu>1.0</mu><mu2>1.0</mu2></ode></friction></surface>
        </collision>
        <!-- No visual: the floor tiles sit exactly at z=0 and would
             z-fight with this plane, flickering in the camera image and
             polluting features. Collision only is enough here. -->
      </link>
    </model>
""")

# ---------------- Floor tiles (visual only) ----------------
# The tile top must sit exactly at z=0. The wheels ride on ground_plane
# (z=0), so raising the tiles offsets what the depth camera calls "floor"
# and shifts min_obstacle_height by the same amount.
w('    <model name="floor_tiles">')
w('      <static>true</static>')
w('      <link name="link">')
n = 0
for x in frange(-ROOM_X, ROOM_X, SEG):
    for y in frange(-ROOM_Y, ROOM_Y, SEG):
        cx, cy = x + SEG / 2, y + SEG / 2
        box_visual(f'tile_{n}', f'{cx} {cy} -0.005 0 0 0',
                   f'{SEG} {SEG} 0.01', 'floor.png')
        n += 1
w('      </link>')
w('    </model>')

# ---------------- Outer walls ----------------
w('    <model name="walls">')
w('      <static>true</static>')
w('      <link name="link">')
# Unique texture per segment: identical walls make RTAB-Map mistake one
# place for another and close a false loop.
seg = 0
n = 0
# x = +-ROOM_X walls, split along y
for sx in (ROOM_X, -ROOM_X):
    for y in frange(-ROOM_Y, ROOM_Y, SEG):
        cy = y + SEG / 2
        pose = f'{sx} {cy} {WALL_H/2} 0 0 0'
        size = f'{WALL_T} {SEG} {WALL_H}'
        box_visual(f'wall_x_{n}', pose, size, f'wall_{seg:02d}.png')
        box_collision(f'wall_x_col_{n}', pose, size)
        n += 1
        seg += 1
# y = +-ROOM_Y walls, split along x
n = 0
for sy in (ROOM_Y, -ROOM_Y):
    for x in frange(-ROOM_X, ROOM_X, SEG):
        cx = x + SEG / 2
        pose = f'{cx} {sy} {WALL_H/2} 0 0 0'
        size = f'{SEG} {WALL_T} {WALL_H}'
        box_visual(f'wall_y_{n}', pose, size, f'wall_{seg:02d}.png')
        box_collision(f'wall_y_col_{n}', pose, size)
        n += 1
        seg += 1
w('      </link>')
w('    </model>')

# ---------------- Partitions ----------------
# A zig-zag route is needed to exercise loop closure.
PARTITIONS = [
    # (cx, cy, len_x, len_y)
    (-1.5, -2.5, WALL_T, 3.0),
    (1.5, 2.5, WALL_T, 3.0),
]
w('    <model name="partitions">')
w('      <static>true</static>')
w('      <link name="link">')
for i, (cx, cy, lx, ly) in enumerate(PARTITIONS):
    pose = f'{cx} {cy} {WALL_H/2} 0 0 0'
    size = f'{lx} {ly} {WALL_H}'
    box_visual(f'part_{i}', pose, size, f'wall_{seg + i:02d}.png')
    box_collision(f'part_col_{i}', pose, size)
w('      </link>')
w('    </model>')

# ---------------- Narrow corridor bank ----------------
# The robot is 0.40 m wide. Several widths are needed to reproduce "fits
# geometrically but cannot pass".
#
# Each gap is CORRIDOR_D deep, so it is a short corridor rather than a thin
# door: alignment must hold along its length, not just for one instant.
#
# x=-3.0 splits the room and must always be passable; x=+3.2 collects the
# narrower test widths.
DOOR_X = -3.0
DOOR_GAP = 0.80
CORRIDOR_D = 0.60          # corridor depth (= length)

# (label, x, gap centre y, gap width, wall depth)
PASSAGES = [
    ('main',  DOOR_X,  0.0, DOOR_GAP, WALL_T),        # thin 0.80 door
    ('c090',   3.2,    2.6, 0.90, CORRIDOR_D),
    ('c070',   3.2,    0.6, 0.70, CORRIDOR_D),
    ('c060',   3.2,   -3.0, 0.60, CORRIDOR_D),
    ('c055',   3.2,   -1.6, 0.55, CORRIDOR_D),
]


def passage_wall(label, x, gap_cy, gap_w, depth, y_lo, y_hi, tex_base):
    """Build a wall from y_lo to y_hi leaving one gap.

    The two pieces get different textures so they cannot be confused for
    each other.
    """
    for k, (a, b) in enumerate(((y_lo, gap_cy - gap_w / 2),
                                (gap_cy + gap_w / 2, y_hi))):
        if b - a <= 0.01:
            continue
        cy, ln = (a + b) / 2, b - a
        pose = f'{x} {cy} {WALL_H/2} 0 0 0'
        size = f'{depth} {ln} {WALL_H}'
        box_visual(f'{label}_{k}', pose, size, f'wall_{tex_base + k:02d}.png')
        box_collision(f'{label}_col_{k}', pose, size)


w('    <model name="passages">')
w('      <static>true</static>')
w('      <link name="link">')
# x=-3.0: splits the room, one gap. Texture indices avoid the outer walls
# (0-17) and partitions (18-19).
passage_wall('main', DOOR_X, 0.0, DOOR_GAP, WALL_T, -ROOM_Y, ROOM_Y, 26)
# x=+3.2: test wall with three gaps; the spans between them are filled.
_gaps = sorted((cy - gw / 2, cy + gw / 2) for _, _x, cy, gw, _d in PASSAGES[1:])
_walls, _y = [], -ROOM_Y
for _a, _b in _gaps:
    if _a - _y > 0.01:
        _walls.append((_y, _a))
    _y = _b
if ROOM_Y - _y > 0.01:
    _walls.append((_y, ROOM_Y))
for _i, (_a, _b) in enumerate(_walls):
    _cy, _ln = (_a + _b) / 2, _b - _a
    _pose = f'3.2 {_cy} {WALL_H/2} 0 0 0'
    _size = f'{CORRIDOR_D} {_ln} {WALL_H}'
    box_visual(f'corr_{_i}', _pose, _size, f'wall_{21 + _i:02d}.png')
    box_collision(f'corr_col_{_i}', _pose, _size)
w('      </link>')
w('    </model>')

# ---------------- Posters ----------------
# Distinct art per wall, hung low to suit the camera height (~0.17 m).
POSTERS = [
    # (x, y, yaw, texture)
    (ROOM_X - 0.06, -2.0, 0, 'poster1.png'),
    (ROOM_X - 0.06, 2.0, 0, 'poster2.png'),
    (-ROOM_X + 0.06, -1.0, 0, 'poster3.png'),
    (-ROOM_X + 0.06, 2.5, 0, 'poster4.png'),
    (-3.0, ROOM_Y - 0.06, 1.5708, 'poster5.png'),
    (3.0, ROOM_Y - 0.06, 1.5708, 'poster6.png'),
    (-2.0, -ROOM_Y + 0.06, 1.5708, 'poster7.png'),
    (2.5, -ROOM_Y + 0.06, 1.5708, 'poster8.png'),
]
w('    <model name="posters">')
w('      <static>true</static>')
w('      <link name="link">')
for i, (x, y, yaw, tex) in enumerate(POSTERS):
    box_visual(f'poster_{i}', f'{x} {y} 0.55 0 0 {yaw}', '0.02 0.8 0.6', tex)
w('      </link>')
w('    </model>')

# ---------------- Obstacles ----------------
# Nav2 planning tests and visual landmarks.
CRATES = [
    # Keep x=3.2 clear: the corridor test wall runs through it.
    (4.5, 3.4, 0.25, 0.5),
    (-3.4, 1.6, 0.3, 0.6),
    (0.6, 3.0, 0.2, 0.4),
    (-0.5, -3.2, 0.25, 0.5),
]
for i, (x, y, h, s) in enumerate(CRATES):
    w(f"""    <model name="crate_{i}">
      <static>true</static>
      <pose>{x} {y} {h} 0 0 {0.3 * i}</pose>
      <link name="link">
        <collision name="collision">
          <geometry><box><size>{s} {s} {2*h}</size></box></geometry>
        </collision>
        <visual name="visual">
          <geometry><box><size>{s} {s} {2*h}</size></box></geometry>
{pbr('crate.png')}
        </visual>
      </link>
    </model>""")

# ---------------- Low obstacles (lidar blind spot) ----------------
# The lidar plane is 0.49 m above ground; anything lower is the camera's job.
LOW_OBSTACLES = [
    # (x, y, height [m], footprint [m], colour)
    (1.8, -0.6, 0.03, 0.30, (0.9, 0.6, 0.1)),   # 3 cm threshold
    (-1.0, 1.2, 0.05, 0.25, (0.9, 0.3, 0.6)),   # 5 cm box
    (2.6, 1.4, 0.10, 0.20, (0.2, 0.8, 0.8)),    # 10 cm box
]
for i, (x, y, h, sz, c) in enumerate(LOW_OBSTACLES):
    w(f"""    <model name="low_obstacle_{i}">
      <static>true</static>
      <pose>{x} {y} {h/2} 0 0 0</pose>
      <link name="link">
        <collision name="collision">
          <geometry><box><size>{sz} {sz} {h}</size></box></geometry>
        </collision>
        <visual name="visual">
          <geometry><box><size>{sz} {sz} {h}</size></box></geometry>
          <material>
            <ambient>{c[0]} {c[1]} {c[2]} 1</ambient>
            <diffuse>{c[0]} {c[1]} {c[2]} 1</diffuse>
          </material>
        </visual>
      </link>
    </model>""")

# ---------------- Multi-level shelves (sensor split test) ----------------
# The clearest structure for showing the two sensors see different things.
#
#   lidar : a thin disc at 0.4908 m -- only what crosses that height
#   D435i : 0.36 m, pitched 15 deg down -- low and near objects
#
# Shelf heights create three cases:
#
#   shelf_0 : shelf crosses the lidar plane -- looks like a wall in 2D
#   shelf_1 : shelf clears the plane -- lidar sees only four legs and reads
#             it as passable, but the robot body does not fit. Nav2 routes
#             through here without the STVL voxel layer.
#   shelf_2 : closed sides -- lidar sees the panel, camera sees the goods
#
# (name, x, y, yaw, width, depth, [shelf heights], leg size, side panels)
SHELVES = [
    ('shelf_0', -4.55, -2.0, 0.0, 1.40, 0.35, [0.06, 0.49, 0.95, 1.40], 0.06, False),
    ('shelf_1',  2.40,  3.60, 1.5708, 1.40, 0.35, [0.06, 0.90, 1.45], 0.05, False),
    ('shelf_2',  4.55, -0.60, 0.0, 1.20, 0.35, [0.06, 0.55, 1.05, 1.45], 0.06, True),
]
BOARD_T = 0.04
# Goods on the shelves; a different colour each aids place recognition.
SHELF_ITEMS = {
    'shelf_0': [(0, -0.45, 0.16, (0.85, 0.25, 0.2)), (1, 0.30, 0.13, (0.2, 0.5, 0.85)),
                (2, -0.15, 0.18, (0.9, 0.75, 0.2))],
    'shelf_1': [(0, 0.40, 0.15, (0.25, 0.7, 0.35)), (1, -0.35, 0.20, (0.7, 0.3, 0.75))],
    'shelf_2': [(1, -0.30, 0.14, (0.95, 0.55, 0.15)), (2, 0.25, 0.17, (0.15, 0.65, 0.7)),
                (3, 0.00, 0.12, (0.6, 0.6, 0.65))],
}

for name, sx, sy, yaw, wid, dep, boards, leg, sides in SHELVES:
    top = boards[-1] + BOARD_T / 2.0
    w(f"""    <model name="{name}">
      <static>true</static>
      <pose>{sx} {sy} 0 0 0 {yaw}</pose>
      <link name="link">""")
    # Four legs
    for k, (dx, dy) in enumerate([(1, 1), (1, -1), (-1, 1), (-1, -1)]):
        lx = dx * (wid / 2.0 - leg / 2.0)
        ly = dy * (dep / 2.0 - leg / 2.0)
        pose = f'{lx} {ly} {top/2.0} 0 0 0'
        size = f'{leg} {leg} {top}'
        box_visual(f'{name}_leg_{k}', pose, size, 'crate.png')
        box_collision(f'{name}_legc_{k}', pose, size)
    # Shelves
    for k, bz in enumerate(boards):
        pose = f'0 0 {bz} 0 0 0'
        size = f'{wid} {dep} {BOARD_T}'
        box_visual(f'{name}_board_{k}', pose, size, 'crate.png')
        box_collision(f'{name}_boardc_{k}', pose, size)
    # Always a back panel: the shelves sit against a wall.
    back_pose = f'0 {-(dep/2.0 - 0.01)} {top/2.0} 0 0 0'
    back_size = f'{wid} 0.02 {top}'
    box_visual(f'{name}_back', back_pose, back_size, 'crate.png')
    box_collision(f'{name}_backc', back_pose, back_size)
    if sides:
        for k, dx in enumerate((1, -1)):
            pose = f'{dx * (wid/2.0 - 0.01)} 0 {top/2.0} 0 0 0'
            size = f'0.02 {dep} {top}'
            box_visual(f'{name}_side_{k}', pose, size, 'crate.png')
            box_collision(f'{name}_sidec_{k}', pose, size)
    # Goods, with collision: these are the 3D obstacles the camera must see.
    for k, (bi, off, isz, c) in enumerate(SHELF_ITEMS.get(name, [])):
        iz = boards[bi] + BOARD_T / 2.0 + isz / 2.0
        w(f"""        <collision name="{name}_item_c{k}">
          <pose>{off} 0 {iz} 0 0 0</pose>
          <geometry><box><size>{isz} {isz} {isz}</size></box></geometry>
        </collision>
        <visual name="{name}_item_{k}">
          <pose>{off} 0 {iz} 0 0 0</pose>
          <geometry><box><size>{isz} {isz} {isz}</size></box></geometry>
          <material>
            <ambient>{c[0]} {c[1]} {c[2]} 1</ambient>
            <diffuse>{c[0]} {c[1]} {c[2]} 1</diffuse>
          </material>
        </visual>""")
    w('      </link>')
    w('    </model>')

PILLARS = [
    (2.0, 0.5, 0.25, 0.9, (0.8, 0.3, 0.2)),
    (-2.2, -0.8, 0.22, 0.8, (0.2, 0.6, 0.35)),
    (0.0, 1.8, 0.2, 0.7, (0.85, 0.7, 0.2)),
]
for i, (x, y, r, h, c) in enumerate(PILLARS):
    w(f"""    <model name="pillar_{i}">
      <static>true</static>
      <pose>{x} {y} {h/2} 0 0 0</pose>
      <link name="link">
        <collision name="collision">
          <geometry><cylinder><radius>{r}</radius><length>{h}</length></cylinder></geometry>
        </collision>
        <visual name="visual">
          <geometry><cylinder><radius>{r}</radius><length>{h}</length></cylinder></geometry>
          <material>
            <ambient>{c[0]} {c[1]} {c[2]} 1</ambient>
            <diffuse>{c[0]} {c[1]} {c[2]} 1</diffuse>
          </material>
        </visual>
      </link>
    </model>""")

# ---------------- Charging dock ----------------
# On the south wall: 1.5 m of clear approach and reachable without passing
# the narrow corridor bank at x=3.2.
#
# Marker height is chosen to minimise the distance at which the camera
# loses them; h = 0.316 is the optimum. A lower dock looks natural but
# crops the markers out of frame much earlier. See CLAUDE.md.
DOCK_X = 1.0
DOCK_WALL_Y = -ROOM_Y + WALL_T / 2.0    # inner wall face = -3.95
DOCK_PANEL_T = 0.05                     # back panel thickness
DOCK_PANEL_W = 0.52
DOCK_PANEL_H = 0.45
DOCK_PLATE = 0.14                       # marker tile edge (whole texture)
DOCK_MARKER = 0.10                      # black square edge
DOCK_MARKER_Z = 0.31                    # marker centre height
# Marker layout, left/centre/right = id 1/0/2. dock_marker_board.py must
# use the same layout to solve them as one board.
DOCK_MARKER_DX = (-0.16, 0.0, 0.16)
DOCK_MARKER_IDS = (1, 0, 2)

# --- Contacts: two copper plates on the floor ---
# Real layout: +/- plates on the station floor, two 6-pin pogo blocks under
# the robot rear. Driving over them compresses the pins.
#
# The plates cannot lie flat. Ground clearance is 60 mm and the costmap
# ignores anything under 30 mm, so the bracket must sit between 30 and
# 60 mm (45 mm here) with the plate raised to 40 mm; the pogo stroke
# covers the remaining 5 mm.
#
# Lateral: wheels at +-0.17 and casters at +-0.14 leave a clear band at
# |y| < 0.11. A wheel riding onto a plate lifts the robot and keeps the
# bracket gap unchanged.
#
# 75 x 100 mm is the real part size.
#
# Contact tolerance subtracts the pin array (6.1 x 3.5 mm), not the
# bracket, from the plate: +-48 mm longitudinal, +-34 mm lateral. Using the
# bracket instead would demand alignment accuracy that contact never needs.
# See CLAUDE.md for the derivation.
DOCK_PLATE_LAT = 0.055                  # plate centre offset, lateral
DOCK_PLATE_W = 0.075                    # plate width (real part)
DOCK_PLATE_L = 0.10                     # plate length (real part)
# Pogo connector: 6 pins, 2x3, 2.54 mm pitch, the 3-pin axis across the
# robot. Contact tolerance derives from this.
DOCK_PIN_PITCH = 0.00254
DOCK_PIN_DIA = 0.001                    # plunger diameter
DOCK_PIN_W = 2 * DOCK_PIN_PITCH + DOCK_PIN_DIA   # across (3 pins)
DOCK_PIN_L = 1 * DOCK_PIN_PITCH + DOCK_PIN_DIA   # along (2 pins)
DOCK_PLATE_Z = 0.04                     # plate top height
DOCK_PLATE_BACK = 0.10                  # behind the robot centre (bracket)
DOCK_BRACKET_Z = 0.045                  # bracket underside; match the URDF
DOCK_COPPER = (0.72, 0.45, 0.20)

# --- No guide walls ---
# The real station has none, so nothing corrects heading mechanically and
# the final pose rests entirely on marker accuracy -- which is why there
# are three markers, not one. A guide channel would also be narrower than
# twice the inscribed radius, painting its interior as a collision.

_panel_front = DOCK_WALL_Y + DOCK_PANEL_T               # -3.90

# Docking direction. Must match docking.yaml's reverse_dock: the plate
# position below flips with it.
#
# Reverse docking keeps the camera facing the room while charging; visual
# odometry breaks down 0.3 m from a wall.
#
# DOCK_ROBOT_Y is this generator's reference pose for placing the plates.
# The marker face lands at y = -3.894; where the robot actually stops is
# set by docking.yaml's dock_distance, not here.
REVERSE_DOCK = True
DOCK_ROBOT_Y = -3.67 if REVERSE_DOCK else -3.60
DOCK_CAM_REACH = 0.2125                 # orinbot.urdf.xacro: base_length/2 + 0.0125
# The marker tile is recessed 2 mm: flush faces z-fight and make detection
# flicker frame to frame.
_plate_t = 0.008
_plate_cy = _panel_front - 0.002 + _plate_t / 2.0

w(f"""    <model name="dock_station">
      <static>true</static>
      <link name="link">""")
# Back panel
box_visual('dock_panel',
           f'{DOCK_X} {DOCK_WALL_Y + DOCK_PANEL_T/2.0} {DOCK_PANEL_H/2.0} 0 0 0',
           f'{DOCK_PANEL_W} {DOCK_PANEL_T} {DOCK_PANEL_H}', 'dock_body.png')
box_collision('dock_panel_c',
              f'{DOCK_X} {DOCK_WALL_Y + DOCK_PANEL_T/2.0} {DOCK_PANEL_H/2.0} 0 0 0',
              f'{DOCK_PANEL_W} {DOCK_PANEL_T} {DOCK_PANEL_H}')
# Marker tiles (no collision: recessed into the panel)
for _dx, _mid in zip(DOCK_MARKER_DX, DOCK_MARKER_IDS):
    box_visual(f'dock_marker_{_mid}',
               f'{DOCK_X + _dx} {_plate_cy} {DOCK_MARKER_Z} 0 0 0',
               f'{DOCK_PLATE} {_plate_t} {DOCK_PLATE}',
               f'dock_marker_{_mid}.png')



def colored_box(name, pose, size, rgb, collision=True):
    w(f"""      <visual name="{name}">
        <pose>{pose}</pose>
        <geometry><box><size>{size}</size></box></geometry>
        <material>
          <ambient>{rgb[0]} {rgb[1]} {rgb[2]} 1</ambient>
          <diffuse>{rgb[0]} {rgb[1]} {rgb[2]} 1</diffuse>
          <specular>0.3 0.3 0.3 1</specular>
        </material>
      </visual>""")
    if collision:
        box_collision(f'{name}_c', pose, size)


# Two floor plates the rear bracket rides onto. Electrical contact is not
# simulated -- battery_sim.py judges it geometrically. The robot faces the
# dock, so its long axis is world y. The pogo pins sit behind the robot
# centre, so reverse docking puts the plates toward the wall.
_plate_y = DOCK_ROBOT_Y + (-DOCK_PLATE_BACK if REVERSE_DOCK else DOCK_PLATE_BACK)
for _k, _s in enumerate((-1, 1)):
    colored_box(
        f'dock_plate_{_k}',
        f'{DOCK_X + _s * DOCK_PLATE_LAT} {_plate_y} {DOCK_PLATE_Z/2.0} 0 0 0',
        f'{DOCK_PLATE_W} {DOCK_PLATE_L} {DOCK_PLATE_Z}',
        DOCK_COPPER)

w('      </link>')
w('    </model>')

# Print the values that have to be kept in sync elsewhere.
_marker_front = _plate_cy + _plate_t / 2.0
_cam_front = DOCK_ROBOT_Y - DOCK_CAM_REACH
sys.stderr.write(
    'docking.yaml home_dock.pose: [%.3f, %.3f, -1.5708]\n'
    '  camera front y=%.4f, clearance to marker tile %+.1f mm\n'
    '  plate top %.0f mm / bracket underside %.0f mm -> pogo stroke %.0f mm\n'
    '  pin array %.1f x %.1f mm -> tolerance %.1f mm long, %.1f mm lat\n'
    % (DOCK_X, DOCK_ROBOT_Y, _cam_front, (_cam_front - _marker_front) * 1000,
       DOCK_PLATE_Z * 1000, DOCK_BRACKET_Z * 1000,
       (DOCK_BRACKET_Z - DOCK_PLATE_Z) * 1000,
       DOCK_PIN_W * 1000, DOCK_PIN_L * 1000,
       (DOCK_PLATE_L - DOCK_PIN_L) / 2.0 * 1000,
       (DOCK_PLATE_W - DOCK_PIN_W) / 2.0 * 1000))

# The dock is below the lidar plane, but it only protrudes 0.115 m from a
# wall the lidar does see, and inflation is 0.40 m, so no path cuts through
# it. The camera (STVL / RTAB-Map grid) sees the dock itself.

w('  </world>')
w('</sdf>')

sys.stdout.write('\n'.join(out) + '\n')
