#!/usr/bin/env python3
"""Office world: plain walls, furniture and moving people.

    python3 generate_office.py > office.sdf      (summary goes to stderr)

The other worlds use high-contrast brick everywhere. Real offices do not, so
this world is deliberately hard:

1. Walls are nearly featureless (office_*.png, low contrast). Visual odometry
   fails on a blank wall no matter how good the depth is, so the furniture
   supplies the features -- as it does indoors.
2. Three moving people: obstacles appear from nowhere, leave ghosts in the
   RTAB-Map grid, and block paths. The only case where the Wait recovery is
   meaningful, since they move on.
3. Furniture as low obstacles: a 0.75 m desk top crosses the lidar plane, but
   chair legs look passable and shelf undersides are empty -- invisible
   without the STVL voxel layer.

20 x 14 m, south wall at y = -4.0 so docking.yaml's dock pose carries over
(cross-checked below).

People are driven by gz-sim-velocity-control-system subscribing to
/model/<name>/cmd_vel, with people_sim.py walking them along the corridors.
No actor meshes are downloaded, so it works offline.
"""

import math
import os
import re
import sys

TEX = 'model://room_materials/materials/textures'

X0, X1 = -10.0, 10.0
Y0, Y1 = -4.0, 10.0              # Y0 fixed by the dock pose
WALL_H = 2.4
WALL_T = 0.12
SEG = 2.5

COR_A = (-0.9, 0.9)              # south corridor (E-W)
COR_B = (5.1, 6.9)               # north corridor (E-W)
PART_X = (-6.0, -2.0, 2.0, 6.0)  # room partition x
DOOR = 0.9

out = []
_tex = 0


def w(s=''):
    out.append(s)


def tex():
    global _tex
    t = _tex
    _tex += 1
    return '%s/office_%03d.png' % (TEX, t)


def vis(name, pose, size, texture):
    w(f"""      <visual name="{name}">
        <pose>{pose}</pose>
        <geometry><box><size>{size}</size></box></geometry>
        <material><diffuse>1 1 1 1</diffuse><pbr><metal>
          <albedo_map>{texture}</albedo_map><roughness>0.92</roughness>
        </metal></pbr></material>
      </visual>""")


def col(name, pose, size):
    w(f"""      <collision name="{name}">
        <pose>{pose}</pose>
        <geometry><box><size>{size}</size></box></geometry>
      </collision>""")


def slab(name, cx, cy, sx, sy, h=WALL_H):
    w(f'    <model name="{name}">')
    w('      <static>true</static>')
    w(f'      <pose>{cx:.4f} {cy:.4f} {h/2:.4f} 0 0 0</pose>')
    w('      <link name="link">')
    col('c', '0 0 0 0 0 0', f'{sx:.4f} {sy:.4f} {h:.4f}')
    vis('v', '0 0 0 0 0 0', f'{sx:.4f} {sy:.4f} {h:.4f}', tex())
    w('      </link>')
    w('    </model>')


def furniture(name, cx, cy, sx, sy, sz, z0, texture):
    """One piece of furniture. The walls are plain, so features come from here."""
    w(f'    <model name="{name}">')
    w('      <static>true</static>')
    w(f'      <pose>{cx:.3f} {cy:.3f} {z0 + sz/2:.3f} 0 0 0</pose>')
    w('      <link name="link">')
    col('c', '0 0 0 0 0 0', f'{sx:.3f} {sy:.3f} {sz:.3f}')
    vis('v', '0 0 0 0 0 0', f'{sx:.3f} {sy:.3f} {sz:.3f}', f'{TEX}/{texture}')
    w('      </link>')
    w('    </model>')


def person(name, cx, cy, rgb):
    """One pedestrian; people_sim.py drives the velocity over ROS.

    Gravity is off: a 0.22 m radius, 1.7 m tall cylinder falls over, and a
    person balances instead. Velocity control sets the speed every step, so
    a collision does not push them aside -- which matches how people treat
    robots and makes the test harder, not easier.

    Inertia is large; a small one spins on contact torque.
    """
    w(f'    <model name="{name}">')
    w(f'      <pose>{cx:.2f} {cy:.2f} 0.85 0 0 0</pose>')
    w('      <link name="link">')
    w('        <gravity>false</gravity>')
    w('        <inertial><mass>70</mass><inertia>'
      '<ixx>200</ixx><iyy>200</iyy><izz>200</izz>'
      '<ixy>0</ixy><ixz>0</ixz><iyz>0</iyz></inertia></inertial>')
    w('        <collision name="c"><geometry>'
      '<cylinder><radius>0.22</radius><length>1.70</length></cylinder>'
      '</geometry></collision>')
    w('        <visual name="v"><geometry>'
      '<cylinder><radius>0.22</radius><length>1.70</length></cylinder></geometry>')
    w(f'          <material><ambient>{rgb}</ambient><diffuse>{rgb}</diffuse>'
      '<specular>0.2 0.2 0.2 1</specular></material>')
    w('        </visual>')
    w('      </link>')
    w('      <plugin filename="gz-sim-velocity-control-system"'
      ' name="gz::sim::systems::VelocityControl">')
    w(f'        <topic>/model/{name}/cmd_vel</topic>')
    w('      </plugin>')
    w('    </model>')


def frange(a, b, s):
    v = a
    while v < b - 1e-6:
        yield v
        v += s


# ====================================================================
w('<?xml version="1.0" ?>')
w('<!-- Generated by generate_office.py. Edit the generator. -->')
w('<sdf version="1.9">')
w('  <world name="office">')
w("""
    <physics name="1ms" type="ignored">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>
    <plugin filename="gz-sim-contact-system" name="gz::sim::systems::Contact"/>
    <gravity>0 0 -9.8</gravity>
    <scene>
      <ambient>0.7 0.7 0.7 1</ambient>
      <background>0.8 0.85 0.9 1</background>
      <shadows>true</shadows>
    </scene>
    <!-- Soft shadows: on plain walls a hard shadow edge becomes the only
         feature, and the map then moves with the lighting. -->
    <light type="directional" name="ceil1">
      <cast_shadows>true</cast_shadows><pose>0 0 6 0 0 0</pose>
      <diffuse>0.55 0.55 0.55 1</diffuse><specular>0.05 0.05 0.05 1</specular>
      <direction>-0.3 0.2 -0.93</direction>
    </light>
    <light type="directional" name="ceil2">
      <cast_shadows>false</cast_shadows><pose>0 0 6 0 0 0</pose>
      <diffuse>0.4 0.4 0.42 1</diffuse><specular>0 0 0 1</specular>
      <direction>0.4 -0.3 -0.87</direction>
    </light>
    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>100 100</size></plane></geometry>
          <surface><friction><ode><mu>1.0</mu><mu2>1.0</mu2></ode></friction></surface>
        </collision>
      </link>
    </model>
""")

w('    <model name="floor">')
w('      <static>true</static>')
w(f'      <pose>{(X0+X1)/2:.2f} {(Y0+Y1)/2:.2f} -0.005 0 0 0</pose>')
w('      <link name="link"><visual name="v">')
w(f'        <geometry><box><size>{X1-X0} {Y1-Y0} 0.01</size></box></geometry>')
w('        <material><diffuse>1 1 1 1</diffuse><pbr><metal>')
w(f'          <albedo_map>{TEX}/floor.png</albedo_map><roughness>0.95</roughness>')
w('        </metal></pbr></material>')
w('      </visual></link>')
w('    </model>')

# ---- Outer walls ----
n = 0
for x in frange(X0, X1, SEG):
    ln = min(SEG, X1 - x)
    slab(f'w_s{n}', x + ln / 2, Y0 - WALL_T / 2, ln, WALL_T); n += 1
    slab(f'w_n{n}', x + ln / 2, Y1 + WALL_T / 2, ln, WALL_T); n += 1
for y in frange(Y0, Y1, SEG):
    ln = min(SEG, Y1 - y)
    slab(f'w_w{n}', X0 - WALL_T / 2, y + ln / 2, WALL_T, ln); n += 1
    slab(f'w_e{n}', X1 + WALL_T / 2, y + ln / 2, WALL_T, ln); n += 1
n_wall = n

# ---- Corridor walls, one door per room ----
def corridor_wall(tag, y, xs):
    """Wall along y with a door in the middle of each room span."""
    edges = [X0] + list(xs) + [X1]
    k = 0
    for a, b in zip(edges[:-1], edges[1:]):
        dc = (a + b) / 2.0
        left = dc - DOOR / 2 - a
        right = b - (dc + DOOR / 2)
        if left > 0.05:
            slab(f'{tag}_{k}a', a + left / 2, y, left, WALL_T)
        if right > 0.05:
            slab(f'{tag}_{k}b', b - right / 2, y, right, WALL_T)
        k += 1


corridor_wall('cA_n', COR_A[1], PART_X)      # corridor A north
corridor_wall('cB_s', COR_B[0], PART_X)      # corridor B south
corridor_wall('cB_n', COR_B[1], PART_X)      # corridor B north

# ---- Room partitions ----
for i, px in enumerate(PART_X):
    slab(f'p1_{i}', px, (COR_A[1] + COR_B[0]) / 2, WALL_T, COR_B[0] - COR_A[1])
    slab(f'p2_{i}', px, (COR_B[1] + Y1) / 2, WALL_T, Y1 - COR_B[1])

# ---- Furniture ----
# The main source of features, since the walls are plain.
POSTERS = ['poster%d.png' % i for i in range(1, 9)]
nf = 0
room_bands = [(COR_A[1], COR_B[0]), (COR_B[1], Y1)]
edges = [X0] + list(PART_X) + [X1]
for band_i, (by0, by1) in enumerate(room_bands):
    for r, (a, b) in enumerate(zip(edges[:-1], edges[1:])):
        cx = (a + b) / 2.0
        cy = (by0 + by1) / 2.0
        t = POSTERS[(band_i * 5 + r) % len(POSTERS)]
        # Desk: top at 0.75, above the lidar plane, so visible in 2D
        furniture(f'desk_{nf}', cx - 0.9, cy + 0.4, 1.40, 0.70, 0.06, 0.72, t)
        furniture(f'desk_{nf}_l1', cx - 1.5, cy + 0.4, 0.06, 0.66, 0.72, 0.0, 'crate.png')
        furniture(f'desk_{nf}_l2', cx - 0.3, cy + 0.4, 0.06, 0.66, 0.72, 0.0, 'crate.png')
        # Chair: seat at 0.45, below the lidar plane; camera only
        furniture(f'chair_{nf}', cx - 0.9, cy - 0.35, 0.45, 0.45, 0.05, 0.43, 'crate.png')
        furniture(f'chair_{nf}_b', cx - 0.9, cy - 0.55, 0.45, 0.06, 0.50, 0.43, t)
        # Shelf against the wall
        furniture(f'shelf_{nf}', cx + 1.3, by1 - 0.35, 0.90, 0.40, 1.80, 0.0, t)
        nf += 1

# ---- Three moving people ----
#
# Keep them clear of the robot spawn: a 70 kg body overlapping the robot at
# spawn makes Gazebo resolve the penetration by throwing both.
ROBOT_SPAWN = (0.0, -2.0)
# Start poses; the routes live in people_sim.py ROUTES.
_people = [
    ('person_0', -8.0, 0.0, '0.85 0.30 0.25 1'),     # corridor A, west end
    ('person_1', 8.0, 6.0, '0.25 0.45 0.85 1'),      # corridor B, east end
    ('person_2', -8.0, -1.6, '0.25 0.70 0.35 1'),    # lobby, west end
]
for _p in _people:
    d0 = math.dist((_p[1], _p[2]), ROBOT_SPAWN)
    if d0 < 1.5:
        sys.stderr.write('ERROR: %s is only %.2f m from the robot spawn (>=1.5)\n'
                         % (_p[0], d0))
        sys.exit(1)
    person(*_p)

# ====================================================================
# Charging dock; same constants as generate_room.py / docking.yaml / URDF
# Must match docking.yaml's reverse_dock: the plate position flips with it.
# Geometry rationale is in generate_room.py.
REVERSE_DOCK = True
DOCK_X, DOCK_ROBOT_Y = 1.0, (-3.67 if REVERSE_DOCK else -3.60)
DOCK_WALL_Y = Y0 + WALL_T / 2.0
DOCK_PANEL_T, DOCK_PANEL_W, DOCK_PANEL_H = 0.05, 0.52, 0.45
DOCK_PLATE, DOCK_MARKER_Z = 0.14, 0.31
DOCK_MARKER_DX, DOCK_MARKER_IDS = (-0.16, 0.0, 0.16), (1, 0, 2)
DOCK_PLATE_LAT, DOCK_PLATE_W, DOCK_PLATE_L = 0.055, 0.075, 0.10
DOCK_PLATE_Z, DOCK_PLATE_BACK = 0.04, 0.10
_pf = DOCK_WALL_Y + DOCK_PANEL_T
_pt = 0.008
_pcy = _pf - 0.002 + _pt / 2.0

w('    <model name="dock_station">')
w('      <static>true</static>')
w('      <link name="link">')
vis('dock_panel', f'{DOCK_X} {DOCK_WALL_Y + DOCK_PANEL_T/2} {DOCK_PANEL_H/2} 0 0 0',
    f'{DOCK_PANEL_W} {DOCK_PANEL_T} {DOCK_PANEL_H}', f'{TEX}/dock_body.png')
col('dock_panel_c', f'{DOCK_X} {DOCK_WALL_Y + DOCK_PANEL_T/2} {DOCK_PANEL_H/2} 0 0 0',
    f'{DOCK_PANEL_W} {DOCK_PANEL_T} {DOCK_PANEL_H}')
for _dx, _mid in zip(DOCK_MARKER_DX, DOCK_MARKER_IDS):
    vis(f'dock_marker_{_mid}', f'{DOCK_X + _dx} {_pcy} {DOCK_MARKER_Z} 0 0 0',
        f'{DOCK_PLATE} {_pt} {DOCK_PLATE}', f'{TEX}/dock_marker_{_mid}.png')
# The pogo pins sit behind the robot, so reverse docking puts the plates
# toward the wall.
_py = DOCK_ROBOT_Y + (-DOCK_PLATE_BACK if REVERSE_DOCK else DOCK_PLATE_BACK)
for _k, _s in enumerate((-1, 1)):
    p = f'{DOCK_X + _s*DOCK_PLATE_LAT} {_py} {DOCK_PLATE_Z/2} 0 0 0'
    s = f'{DOCK_PLATE_W} {DOCK_PLATE_L} {DOCK_PLATE_Z}'
    w(f'      <visual name="dock_plate_{_k}"><pose>{p}</pose>'
      f'<geometry><box><size>{s}</size></box></geometry>'
      '<material><ambient>0.72 0.45 0.20 1</ambient>'
      '<diffuse>0.72 0.45 0.20 1</diffuse></material></visual>')
    col(f'dock_plate_{_k}_c', p, s)
w('      </link>')
w('    </model>')

w('  </world>')
w('</sdf>')

# ---- Cross-check against docking.yaml ----
_y = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                      '..', '..', 'orinbot_navigation', 'config', 'docking.yaml'))
_chk = 'not checked'
try:
    m = re.search(r'home_dock:.*?pose:\s*\[([-0-9.]+),\s*([-0-9.]+)', open(_y).read(), re.S)
    if m:
        px, py = float(m.group(1)), float(m.group(2))
        if abs(px - DOCK_X) > 1e-6 or abs(py - DOCK_ROBOT_Y) > 1e-6:
            sys.stderr.write('ERROR: docking.yaml [%.3f, %.3f] != world [%.3f, %.3f]\n'
                             % (px, py, DOCK_X, DOCK_ROBOT_Y))
            sys.exit(1)
        _chk = 'match [%.2f, %.2f]' % (px, py)
except OSError as exc:                                    # noqa: BLE001
    _chk = 'read failed (%s)' % exc

sys.stdout.write('\n'.join(out) + '\n')
e = sys.stderr.write
e('office %.0f x %.0f m, wall height %.1f m, low-contrast walls\n'
  % (X1 - X0, Y1 - Y0, WALL_H))
e('corridor A y %.1f~%.1f (%.1f m), B y %.1f~%.1f (%.1f m), door %.2f m\n'
  % (COR_A[0], COR_A[1], COR_A[1] - COR_A[0],
     COR_B[0], COR_B[1], COR_B[1] - COR_B[0], DOOR))
e('%d rooms, %d furniture sets (desk/chair/shelf), 3 moving people\n'
  % ((len(edges) - 1) * len(room_bands), nf))
e('textures needed: %d (office_000~%03d)\n' % (_tex, _tex - 1))
e('dock: docking.yaml cross-check %s\n' % _chk)
e('suggested spawn: (0, -2.0), south lobby in front of the dock\n')
