#!/usr/bin/env python3
"""room.sdf default world SDF model generator script.

    python3 generate_room.py > room.sdf
"""

import math
import sys

TEX = 'model://room_materials/materials/textures'

ROOM_X = 5.0          # Wall distance from center (X axis)
ROOM_Y = 4.0          # Wall distance from center (Y axis)
WALL_H = 1.2
WALL_T = 0.1
SEG = 2.0             # Wall segment length

out = []


def w(s=''):
    out.append(s)


def pbr(texture, roughness=0.9):
    return f"""        <material>
          <ambient>1 1 1 1</ambient>
          <diffuse>1 1 1 1</diffuse>
          <specular>0.05 0.05 0.05 1</specular>
          <pbr>
            <metal>
              <albedo_map>{TEX}/{texture}</albedo_map>
              <metalness>0.0</metalness>
              <roughness>{roughness}</roughness>
            </metal>
          </pbr>
        </material>"""


def box_visual(name, pose, size, texture):
    w(f"""      <visual name="{name}">
        <pose>{pose}</pose>
        <geometry><box><size>{size}</size></box></geometry>
        <material>
          <ambient>1 1 1 1</ambient><diffuse>1 1 1 1</diffuse>
          <specular>0.05 0.05 0.05 1</specular>
          <pbr><metal><albedo_map>{TEX}/{texture}</albedo_map><roughness>0.9</roughness></metal></pbr>
        </material>
      </visual>""")


def box_collision(name, pose, size):
    w(f"""      <collision name="{name}">
        <pose>{pose}</pose>
        <geometry><box><size>{size}</size></box></geometry>
      </collision>""")


def frange(a, b, step):
    v = a
    while v < b - 1e-6:
        yield v
        v += step


# ====================================================================
w('<?xml version="1.0" ?>')
w('<!-- Generated by generate_room.py. Do not edit directly; modify generator. -->')
w('<sdf version="1.9">')
w('  <world name="room">')
w("""
    <scene>
      <ambient>0.6 0.6 0.6 1.0</ambient>
      <background>0.8 0.85 0.9 1.0</background>
      <shadows>true</shadows>
      <grid>false</grid>
    </scene>

    <plugin filename="gz-sim-physics-system"
            name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system"
            name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system"
            name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system"
            name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>

    <include>
      <uri>model://ground_plane</uri>
    </include>

    <light type="directional" name="sun">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 8 0 0 0</pose>
      <diffuse>0.7 0.7 0.7 1</diffuse><specular>0.2 0.2 0.2 1</specular>
      <direction>-0.5 0.2 -0.9</direction>
    </light>
    <light type="directional" name="sun2">
      <cast_shadows>false</cast_shadows>
      <pose>-4 3 6 0 0 0</pose>
      <diffuse>0.4 0.4 0.4 1</diffuse><specular>0.0 0.0 0.0 1</specular>
      <direction>0.5 -0.2 -0.8</direction>
    </light>

    <model name="floor_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>20 20</size></plane></geometry>
        </collision>
      </link>
    </model>
""")

# Floor tiles
w('    <model name="floor_tiles">')
w('      <static>true</static>')
w('      <link name="link">')
n = 0
for x in frange(-ROOM_X, ROOM_X, SEG):
    for y in frange(-ROOM_Y, ROOM_Y, SEG):
        box_visual(f'tile_{n}', f'{x + SEG/2:.3f} {y + SEG/2:.3f} -0.005 0 0 0',
                   f'{SEG:.3f} {SEG:.3f} 0.01', 'floor.png')
        n += 1
w('      </link>')
w('    </model>')

# Outer walls
w('    <model name="walls">')
w('      <static>true</static>')
w('      <link name="link">')
seg = 0
n = 0
for sx in (ROOM_X, -ROOM_X):
    for y in frange(-ROOM_Y, ROOM_Y, SEG):
        pose = f'{sx} {y + SEG/2:.3f} {WALL_H/2} 0 0 0'
        size = f'{WALL_T} {SEG:.3f} {WALL_H}'
        box_visual(f'wall_x_{n}', pose, size, f'wall_{seg:02d}.png')
        box_collision(f'wall_x_col_{n}', pose, size)
        n += 1
        seg += 1

n = 0
for sy in (ROOM_Y, -ROOM_Y):
    for x in frange(-ROOM_X, ROOM_X, SEG):
        pose = f'{x + SEG/2:.3f} {sy} {WALL_H/2} 0 0 0'
        size = f'{SEG:.3f} {WALL_T} {WALL_H}'
        box_visual(f'wall_y_{n}', pose, size, f'wall_{seg:02d}.png')
        box_collision(f'wall_y_col_{n}', pose, size)
        n += 1
        seg += 1
w('      </link>')
w('    </model>')

# Interior Partitions
PARTITIONS = [
    (1.0, 1.5, 4.0, WALL_T),
    (-1.0, -1.5, 4.0, WALL_T),
]
w('    <model name="partitions">')
w('      <static>true</static>')
w('      <link name="link">')
for i, (cx, cy, lx, ly) in enumerate(PARTITIONS):
    pose = f'{cx} {cy} {WALL_H/2} 0 0 0'
    size = f'{lx} {ly} {WALL_H}'
    box_visual(f'part_{i}', pose, size, f'wall_{18+i:02d}.png')
    box_collision(f'part_col_{i}', pose, size)
w('      </link>')
w('    </model>')

# Corridor Passages
DOOR_X = -3.0
DOOR_GAP = 0.80
CORRIDOR_D = 0.60

PASSAGES = [
    ('main',  DOOR_X,  0.0, DOOR_GAP, WALL_T),
    ('c090',  3.2,     2.6, 0.90,     CORRIDOR_D),
    ('c070',  3.2,     0.6, 0.70,     CORRIDOR_D),
    ('c055',  3.2,    -1.6, 0.55,     CORRIDOR_D),
    ('c060',  3.2,    -3.0, 0.60,     CORRIDOR_D),
]


def passage_wall(label, x, gap_cy, gap_w, depth, y_lo, y_hi, tex_base):
    y_gap_lo = gap_cy - gap_w / 2.0
    y_gap_hi = gap_cy + gap_w / 2.0

    l1 = y_gap_lo - y_lo
    if l1 > 0.01:
        cy1 = (y_lo + y_gap_lo) / 2.0
        pose = f'{x} {cy1:.3f} {WALL_H/2} 0 0 0'
        size = f'{depth} {l1:.3f} {WALL_H}'
        box_visual(f'{label}_s1', pose, size, f'wall_{tex_base:02d}.png')
        box_collision(f'{label}_col1', pose, size)

    l2 = y_hi - y_gap_hi
    if l2 > 0.01:
        cy2 = (y_gap_hi + y_hi) / 2.0
        pose = f'{x} {cy2:.3f} {WALL_H/2} 0 0 0'
        size = f'{depth} {l2:.3f} {WALL_H}'
        box_visual(f'{label}_s2', pose, size, f'wall_{tex_base+1:02d}.png')
        box_collision(f'{label}_col2', pose, size)


w('    <model name="passages">')
w('      <static>true</static>')
w('      <link name="link">')
passage_wall('main', DOOR_X, 0.0, DOOR_GAP, WALL_T, -ROOM_Y, ROOM_Y, 26)

_gaps = sorted((cy - gw / 2, cy + gw / 2) for _, _x, cy, gw, _d in PASSAGES[1:])
_walls, _y = [], -ROOM_Y
for _a, _b in _gaps:
    if _a - _y > 0.01:
        _walls.append((_y, _a))
    _y = _b
if ROOM_Y - _y > 0.01:
    _walls.append((_y, ROOM_Y))
for _i, (_a, _b) in enumerate(_walls):
    _cy, _ln = (_a + _b) / 2, _b - _a
    _pose = f'3.2 {_cy:.3f} {WALL_H/2} 0 0 0'
    _size = f'{CORRIDOR_D} {_ln:.3f} {WALL_H}'
    box_visual(f'corr_{_i}', _pose, _size, f'wall_{20+_i:02d}.png')
    box_collision(f'corr_col_{_i}', _pose, _size)
w('      </link>')
w('    </model>')

# Posters
POSTERS = [
    (ROOM_X - 0.01,  2.0, 0.0, 'poster_0.png'),
    (ROOM_X - 0.01, -2.0, 0.0, 'poster_1.png'),
    (-ROOM_X + 0.01,  2.0, math.pi, 'poster_2.png'),
    (-ROOM_X + 0.01, -2.0, math.pi, 'poster_3.png'),
    (2.0,  ROOM_Y - 0.01, -math.pi / 2, 'poster_4.png'),
    (-2.0,  ROOM_Y - 0.01, -math.pi / 2, 'poster_5.png'),
    (2.0, -ROOM_Y + 0.01,  math.pi / 2, 'poster_6.png'),
    (-2.0, -ROOM_Y + 0.01,  math.pi / 2, 'poster_7.png'),
]
w('    <model name="posters">')
w('      <static>true</static>')
w('      <link name="link">')
for i, (x, y, yaw, tex) in enumerate(POSTERS):
    box_visual(f'poster_{i}', f'{x} {y} 0.55 0 0 {yaw}', '0.02 0.8 0.6', tex)
w('      </link>')
w('    </model>')

# Crates
CRATES = [
    (2.5, 3.0, 0.45, 0.45),
    (2.5, 2.2, 0.40, 0.40),
    (-4.0, 2.5, 0.50, 0.50),
    (-4.0, 1.8, 0.35, 0.35),
    (0.0, -2.5, 0.45, 0.45),
    (-2.5, -2.5, 0.50, 0.50),
]
for i, (x, y, h, s) in enumerate(CRATES):
    w(f"""    <model name="crate_{i}">
      <static>true</static>
      <link name="link">
        <visual name="v">
          <pose>{x} {y} {h/2} 0 0 0</pose>
          <geometry><box><size>{s} {s} {h}</size></box></geometry>
          <material>
            <ambient>1 1 1 1</ambient><diffuse>1 1 1 1</diffuse>
            <pbr><metal><albedo_map>{TEX}/crate.png</albedo_map></metal></pbr>
          </material>
        </visual>
        <collision name="c">
          <pose>{x} {y} {h/2} 0 0 0</pose>
          <geometry><box><size>{s} {s} {h}</size></box></geometry>
        </collision>
      </link>
    </model>""")

# Low Obstacles
LOW_OBSTACLES = [
    (1.8, -0.6, 0.03, 0.30, (0.9, 0.6, 0.1)),
    (-1.0, 1.2, 0.05, 0.25, (0.9, 0.3, 0.6)),
    (2.6, 1.4, 0.10, 0.20, (0.2, 0.8, 0.8)),
]
for i, (x, y, h, sz, c) in enumerate(LOW_OBSTACLES):
    w(f"""    <model name="low_obstacle_{i}">
      <static>true</static>
      <link name="link">
        <visual name="v">
          <pose>{x} {y} {h/2} 0 0 0</pose>
          <geometry><box><size>{sz} {sz} {h}</size></box></geometry>
          <material>
            <ambient>{c[0]} {c[1]} {c[2]} 1</ambient>
            <diffuse>{c[0]} {c[1]} {c[2]} 1</diffuse>
          </material>
        </visual>
        <collision name="c">
          <pose>{x} {y} {h/2} 0 0 0</pose>
          <geometry><box><size>{sz} {sz} {h}</size></box></geometry>
        </collision>
      </link>
    </model>""")

# Shelves
SHELVES = [
    ('shelf_0', -2.0, 3.2, 0.0, 1.2, 0.45, [0.15, 0.49, 0.90], 0.03, False),
    ('shelf_1', 0.5, 3.2, 0.0, 1.2, 0.45, [0.15, 0.90], 0.03, False),
    ('shelf_2', -4.2, 0.0, math.pi / 2, 1.2, 0.45, [0.15, 0.55, 0.95], 0.03, True),
]
BOARD_T = 0.04
SHELF_ITEMS = {
    'shelf_0': [(0.2, (0.9, 0.2, 0.2), 0.15, 0.12), (0.55, (0.2, 0.9, 0.2), 0.20, 0.15)],
    'shelf_1': [(0.95, (0.2, 0.3, 0.9), 0.25, 0.18)],
    'shelf_2': [(0.2, (0.9, 0.8, 0.1), 0.18, 0.15), (0.6, (0.8, 0.2, 0.8), 0.22, 0.15)],
}

for name, sx, sy, yaw, wid, dep, boards, leg, sides in SHELVES:
    top = boards[-1] + BOARD_T / 2.0
    w(f'    <model name="{name}">')
    w('      <static>true</static>')
    w('      <link name="link">')
    for bx, by in ((-1, -1), (-1, 1), (1, -1), (1, 1)):
        lx = sx + bx * (wid / 2.0 - leg / 2.0)
        ly = sy + by * (dep / 2.0 - leg / 2.0)
        box_visual(f'leg_{bx}_{by}', f'{lx} {ly} {top/2} 0 0 {yaw}',
                   f'{leg} {leg} {top}', 'crate.png')
        box_collision(f'leg_{bx}_{by}_c', f'{lx} {ly} {top/2} 0 0 {yaw}',
                      f'{leg} {leg} {top}')
    for i, bh in enumerate(boards):
        box_visual(f'board_{i}', f'{sx} {sy} {bh} 0 0 {yaw}',
                   f'{wid} {dep} {BOARD_T}', 'crate.png')
        box_collision(f'board_{i}_c', f'{sx} {sy} {bh} 0 0 {yaw}',
                      f'{wid} {dep} {BOARD_T}')
    if sides:
        box_visual('side_w', f'{sx - wid/2.0} {sy} {top/2} 0 0 {yaw}',
                   f'{BOARD_T} {dep} {top}', 'crate.png')
        box_collision('side_w_c', f'{sx - wid/2.0} {sy} {top/2} 0 0 {yaw}',
                      f'{BOARD_T} {dep} {top}')
        box_visual('side_e', f'{sx + wid/2.0} {sy} {top/2} 0 0 {yaw}',
                   f'{BOARD_T} {dep} {top}', 'crate.png')
        box_collision('side_e_c', f'{sx + wid/2.0} {sy} {top/2} 0 0 {yaw}',
                      f'{BOARD_T} {dep} {top}')
    for idx, (bh, col, sz, d_sz) in enumerate(SHELF_ITEMS.get(name, [])):
        px = sx + (idx * 0.3 - 0.15)
        py = sy
        pz = bh + BOARD_T / 2.0 + sz / 2.0
        colored_box(f'item_{idx}', f'{px} {py} {pz} 0 0 {yaw}',
                    f'{d_sz} {d_sz} {sz}', col)
    w('      </link>')
    w('    </model>')

PILLARS = [
    (1.2, -1.8, 0.20, 1.2, (0.8, 0.8, 0.8)),
    (-2.2, -1.2, 0.18, 1.2, (0.7, 0.7, 0.7)),
]
for i, (x, y, r, h, c) in enumerate(PILLARS):
    w(f"""    <model name="pillar_{i}">
      <static>true</static>
      <link name="link">
        <visual name="v">
          <pose>{x} {y} {h/2} 0 0 0</pose>
          <geometry><cylinder><radius>{r}</radius><length>{h}</length></cylinder></geometry>
          <material>
            <ambient>{c[0]} {c[1]} {c[2]} 1</ambient>
            <diffuse>{c[0]} {c[1]} {c[2]} 1</diffuse>
          </material>
        </visual>
        <collision name="c">
          <pose>{x} {y} {h/2} 0 0 0</pose>
          <geometry><cylinder><radius>{r}</radius><length>{h}</length></cylinder></geometry>
        </collision>
      </link>
    </model>""")

# Docking Station
DOCK_X = 1.0
DOCK_WALL_Y = -ROOM_Y + WALL_T / 2.0
DOCK_PANEL_T = 0.05
DOCK_PANEL_W = 0.52
DOCK_PANEL_H = 0.45
DOCK_PLATE = 0.14
DOCK_MARKER = 0.10
DOCK_MARKER_Z = 0.31
DOCK_MARKER_DX = (-0.16, 0.0, 0.16)
DOCK_MARKER_IDS = (1, 0, 2)
DOCK_PLATE_LAT = 0.055
DOCK_PLATE_W = 0.075
DOCK_PLATE_L = 0.10
DOCK_PIN_PITCH = 0.00254
DOCK_PIN_DIA = 0.001
DOCK_PIN_W = 2 * DOCK_PIN_PITCH + DOCK_PIN_DIA
DOCK_PIN_L = 1 * DOCK_PIN_PITCH + DOCK_PIN_DIA
DOCK_PLATE_Z = 0.04
DOCK_PLATE_BACK = 0.10
DOCK_BRACKET_Z = 0.045
DOCK_COPPER = (0.72, 0.45, 0.20)

_panel_front = DOCK_WALL_Y + DOCK_PANEL_T
DOCK_ROBOT_Y = -3.60
DOCK_CAM_REACH = 0.2125
_plate_t = 0.008
_plate_cy = _panel_front - 0.002 + _plate_t / 2.0

w(f"""    <model name="dock_station">
      <static>true</static>
      <link name="link">""")
box_visual('dock_panel',
           f'{DOCK_X} {DOCK_WALL_Y + DOCK_PANEL_T/2.0} {DOCK_PANEL_H/2.0} 0 0 0',
           f'{DOCK_PANEL_W} {DOCK_PANEL_T} {DOCK_PANEL_H}', 'dock_body.png')
box_collision('dock_panel_c',
              f'{DOCK_X} {DOCK_WALL_Y + DOCK_PANEL_T/2.0} {DOCK_PANEL_H/2.0} 0 0 0',
              f'{DOCK_PANEL_W} {DOCK_PANEL_T} {DOCK_PANEL_H}')
for _dx, _mid in zip(DOCK_MARKER_DX, DOCK_MARKER_IDS):
    box_visual(f'dock_marker_{_mid}',
               f'{DOCK_X + _dx} {_plate_cy} {DOCK_MARKER_Z} 0 0 0',
               f'{DOCK_PLATE} {_plate_t} {DOCK_PLATE}',
               f'dock_marker_{_mid}.png')


def colored_box(name, pose, size, rgb, collision=True):
    w(f"""      <visual name="{name}">
        <pose>{pose}</pose>
        <geometry><box><size>{size}</size></box></geometry>
        <material>
          <ambient>{rgb[0]} {rgb[1]} {rgb[2]} 1</ambient>
          <diffuse>{rgb[0]} {rgb[1]} {rgb[2]} 1</diffuse>
        </material>
      </visual>""")
    if collision:
        box_collision(f'{name}_c', pose, size)


_plate_y = DOCK_ROBOT_Y + DOCK_PLATE_BACK
for _k, _s in enumerate((-1, 1)):
    colored_box(
        f'dock_copper_{_k}',
        f'{DOCK_X + _s * DOCK_PLATE_LAT} {_plate_y} {DOCK_PLATE_Z / 2.0} 0 0 0',
        f'{DOCK_PLATE_W} {DOCK_PLATE_L} {DOCK_PLATE_Z}',
        DOCK_COPPER)

w('      </link>')
w('    </model>')

_marker_front = _plate_cy + _plate_t / 2.0
_cam_front = DOCK_ROBOT_Y - DOCK_CAM_REACH

w('  </world>')
w('</sdf>')

sys.stdout.write('\n'.join(out) + '\n')
